/* Generated by gen_gl.py - do not edit. */
#include "gl_fwd.h"
#include "glhost_ops.h"

void APIENTRY glActiveTexture(GLenum texture);
void APIENTRY fw_glActiveTexture(GLenum texture)
{
	uint64_t fa_[1];
	glActiveTexture(texture);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(texture);
	fw_call(GLH_OP_glActiveTexture, fa_, 1, NULL, 0);
}

void APIENTRY glAttachShader(GLuint program, GLuint shader);
void APIENTRY fw_glAttachShader(GLuint program, GLuint shader)
{
	uint64_t fa_[2];
	glAttachShader(program, shader);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fa_[1] = (uint64_t)(shader);
	fw_call(GLH_OP_glAttachShader, fa_, 2, NULL, 0);
}

void APIENTRY glBegin(GLenum mode);
void APIENTRY fw_glBegin(GLenum mode)
{
	uint64_t fa_[1];
	if (!glfwd_on()) {
		glBegin(mode);
		return;
	}
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glBegin, fa_, 1, NULL, 0);
}

void APIENTRY glBeginTransformFeedback(GLenum primitiveMode);
void APIENTRY fw_glBeginTransformFeedback(GLenum primitiveMode)
{
	uint64_t fa_[1];
	glBeginTransformFeedback(primitiveMode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(primitiveMode);
	fw_call(GLH_OP_glBeginTransformFeedback, fa_, 1, NULL, 0);
}

void APIENTRY glBindBuffer(GLenum target, GLuint buffer);
void APIENTRY fw_glBindBuffer(GLenum target, GLuint buffer)
{
	uint64_t fa_[2];
	glBindBuffer(target, buffer);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(buffer);
	fw_call(GLH_OP_glBindBuffer, fa_, 2, NULL, 0);
}

void APIENTRY glBindBufferBase(GLenum target, GLuint index, GLuint buffer);
void APIENTRY fw_glBindBufferBase(GLenum target, GLuint index, GLuint buffer)
{
	uint64_t fa_[3];
	glBindBufferBase(target, index, buffer);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(index);
	fa_[2] = (uint64_t)(buffer);
	fw_call(GLH_OP_glBindBufferBase, fa_, 3, NULL, 0);
}

void APIENTRY glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void APIENTRY fw_glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size)
{
	uint64_t fa_[5];
	glBindBufferRange(target, index, buffer, offset, size);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(index);
	fa_[2] = (uint64_t)(buffer);
	fa_[3] = (uint64_t)(int64_t)(offset);
	fa_[4] = (uint64_t)(int64_t)(size);
	fw_call(GLH_OP_glBindBufferRange, fa_, 5, NULL, 0);
}

void APIENTRY glBindFramebuffer(GLenum target, GLuint framebuffer);
void APIENTRY fw_glBindFramebuffer(GLenum target, GLuint framebuffer)
{
	uint64_t fa_[2];
	glBindFramebuffer(target, framebuffer);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(framebuffer);
	fw_call(GLH_OP_glBindFramebuffer, fa_, 2, NULL, 0);
}

void APIENTRY glBindImageTexture(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
void APIENTRY fw_glBindImageTexture(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format)
{
	uint64_t fa_[7];
	glBindImageTexture(unit, texture, level, layered, layer, access, format);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(unit);
	fa_[1] = (uint64_t)(texture);
	fa_[2] = (uint64_t)(int64_t)(level);
	fa_[3] = (uint64_t)(layered);
	fa_[4] = (uint64_t)(int64_t)(layer);
	fa_[5] = (uint64_t)(access);
	fa_[6] = (uint64_t)(format);
	fw_call(GLH_OP_glBindImageTexture, fa_, 7, NULL, 0);
}

void APIENTRY glBindRenderbuffer(GLenum target, GLuint renderbuffer);
void APIENTRY fw_glBindRenderbuffer(GLenum target, GLuint renderbuffer)
{
	uint64_t fa_[2];
	glBindRenderbuffer(target, renderbuffer);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(renderbuffer);
	fw_call(GLH_OP_glBindRenderbuffer, fa_, 2, NULL, 0);
}

void APIENTRY glBindSampler(GLuint unit, GLuint sampler);
void APIENTRY fw_glBindSampler(GLuint unit, GLuint sampler)
{
	uint64_t fa_[2];
	glBindSampler(unit, sampler);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(unit);
	fa_[1] = (uint64_t)(sampler);
	fw_call(GLH_OP_glBindSampler, fa_, 2, NULL, 0);
}

void APIENTRY glBindTexture(GLenum target,GLuint texture);
void APIENTRY fw_glBindTexture(GLenum target,GLuint texture)
{
	uint64_t fa_[2];
	glBindTexture(target, texture);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(texture);
	fw_call(GLH_OP_glBindTexture, fa_, 2, NULL, 0);
}

void APIENTRY glBindVertexArray(GLuint array);
void APIENTRY fw_glBindVertexArray(GLuint array)
{
	uint64_t fa_[1];
	glBindVertexArray(array);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(array);
	fw_call(GLH_OP_glBindVertexArray, fa_, 1, NULL, 0);
}

void APIENTRY glBlendEquation(GLenum mode);
void APIENTRY fw_glBlendEquation(GLenum mode)
{
	uint64_t fa_[1];
	glBlendEquation(mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glBlendEquation, fa_, 1, NULL, 0);
}

void APIENTRY glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha);
void APIENTRY fw_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha)
{
	uint64_t fa_[2];
	glBlendEquationSeparate(modeRGB, modeAlpha);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(modeRGB);
	fa_[1] = (uint64_t)(modeAlpha);
	fw_call(GLH_OP_glBlendEquationSeparate, fa_, 2, NULL, 0);
}

void APIENTRY glBlendFunc(GLenum sfactor,GLenum dfactor);
void APIENTRY fw_glBlendFunc(GLenum sfactor,GLenum dfactor)
{
	uint64_t fa_[2];
	glBlendFunc(sfactor, dfactor);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(sfactor);
	fa_[1] = (uint64_t)(dfactor);
	fw_call(GLH_OP_glBlendFunc, fa_, 2, NULL, 0);
}

void APIENTRY glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void APIENTRY fw_glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha)
{
	uint64_t fa_[4];
	glBlendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(sfactorRGB);
	fa_[1] = (uint64_t)(dfactorRGB);
	fa_[2] = (uint64_t)(sfactorAlpha);
	fa_[3] = (uint64_t)(dfactorAlpha);
	fw_call(GLH_OP_glBlendFuncSeparate, fa_, 4, NULL, 0);
}

void APIENTRY glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void APIENTRY fw_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter)
{
	uint64_t fa_[10];
	if (!glfwd_on()) {
		glBlitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
		return;
	}
	fa_[0] = (uint64_t)(int64_t)(srcX0);
	fa_[1] = (uint64_t)(int64_t)(srcY0);
	fa_[2] = (uint64_t)(int64_t)(srcX1);
	fa_[3] = (uint64_t)(int64_t)(srcY1);
	fa_[4] = (uint64_t)(int64_t)(dstX0);
	fa_[5] = (uint64_t)(int64_t)(dstY0);
	fa_[6] = (uint64_t)(int64_t)(dstX1);
	fa_[7] = (uint64_t)(int64_t)(dstY1);
	fa_[8] = (uint64_t)(mask);
	fa_[9] = (uint64_t)(filter);
	fw_call(GLH_OP_glBlitFramebuffer, fa_, 10, NULL, 0);
}

void APIENTRY glClear(GLbitfield mask);
void APIENTRY fw_glClear(GLbitfield mask)
{
	uint64_t fa_[1];
	if (!glfwd_on()) {
		glClear(mask);
		return;
	}
	fa_[0] = (uint64_t)(mask);
	fw_call(GLH_OP_glClear, fa_, 1, NULL, 0);
}

void APIENTRY glClearColor(GLclampf red,GLclampf green,GLclampf blue,GLclampf alpha);
void APIENTRY fw_glClearColor(GLclampf red,GLclampf green,GLclampf blue,GLclampf alpha)
{
	uint64_t fa_[4];
	glClearColor(red, green, blue, alpha);
	if (!glfwd_on())
		return;
	fa_[0] = fw_f(red);
	fa_[1] = fw_f(green);
	fa_[2] = fw_f(blue);
	fa_[3] = fw_f(alpha);
	fw_call(GLH_OP_glClearColor, fa_, 4, NULL, 0);
}

void APIENTRY glClearDepth(GLclampd depth);
void APIENTRY fw_glClearDepth(GLclampd depth)
{
	uint64_t fa_[1];
	glClearDepth(depth);
	if (!glfwd_on())
		return;
	fa_[0] = fw_d(depth);
	fw_call(GLH_OP_glClearDepth, fa_, 1, NULL, 0);
}

void APIENTRY glClearDepthf(GLfloat d);
void APIENTRY fw_glClearDepthf(GLfloat d)
{
	uint64_t fa_[1];
	glClearDepthf(d);
	if (!glfwd_on())
		return;
	fa_[0] = fw_f(d);
	fw_call(GLH_OP_glClearDepthf, fa_, 1, NULL, 0);
}

void APIENTRY glClearStencil(GLint s);
void APIENTRY fw_glClearStencil(GLint s)
{
	uint64_t fa_[1];
	glClearStencil(s);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(s);
	fw_call(GLH_OP_glClearStencil, fa_, 1, NULL, 0);
}

void APIENTRY glColor4f(GLfloat red,GLfloat green,GLfloat blue,GLfloat alpha);
void APIENTRY fw_glColor4f(GLfloat red,GLfloat green,GLfloat blue,GLfloat alpha)
{
	uint64_t fa_[4];
	if (!glfwd_on()) {
		glColor4f(red, green, blue, alpha);
		return;
	}
	fa_[0] = fw_f(red);
	fa_[1] = fw_f(green);
	fa_[2] = fw_f(blue);
	fa_[3] = fw_f(alpha);
	fw_call(GLH_OP_glColor4f, fa_, 4, NULL, 0);
}

void APIENTRY glColor4ub(GLubyte red,GLubyte green,GLubyte blue,GLubyte alpha);
void APIENTRY fw_glColor4ub(GLubyte red,GLubyte green,GLubyte blue,GLubyte alpha)
{
	uint64_t fa_[4];
	if (!glfwd_on()) {
		glColor4ub(red, green, blue, alpha);
		return;
	}
	fa_[0] = (uint64_t)(red);
	fa_[1] = (uint64_t)(green);
	fa_[2] = (uint64_t)(blue);
	fa_[3] = (uint64_t)(alpha);
	fw_call(GLH_OP_glColor4ub, fa_, 4, NULL, 0);
}

void APIENTRY glColorMask(GLboolean red,GLboolean green,GLboolean blue,GLboolean alpha);
void APIENTRY fw_glColorMask(GLboolean red,GLboolean green,GLboolean blue,GLboolean alpha)
{
	uint64_t fa_[4];
	glColorMask(red, green, blue, alpha);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(red);
	fa_[1] = (uint64_t)(green);
	fa_[2] = (uint64_t)(blue);
	fa_[3] = (uint64_t)(alpha);
	fw_call(GLH_OP_glColorMask, fa_, 4, NULL, 0);
}

void APIENTRY glColorMaski(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
void APIENTRY fw_glColorMaski(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a)
{
	uint64_t fa_[5];
	glColorMaski(index, r, g, b, a);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = (uint64_t)(r);
	fa_[2] = (uint64_t)(g);
	fa_[3] = (uint64_t)(b);
	fa_[4] = (uint64_t)(a);
	fw_call(GLH_OP_glColorMaski, fa_, 5, NULL, 0);
}

void APIENTRY glCompileShader(GLuint shader);
void APIENTRY fw_glCompileShader(GLuint shader)
{
	uint64_t fa_[1];
	glCompileShader(shader);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(shader);
	fw_call(GLH_OP_glCompileShader, fa_, 1, NULL, 0);
}

void APIENTRY glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void APIENTRY fw_glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size)
{
	uint64_t fa_[5];
	glCopyBufferSubData(readTarget, writeTarget, readOffset, writeOffset, size);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(readTarget);
	fa_[1] = (uint64_t)(writeTarget);
	fa_[2] = (uint64_t)(int64_t)(readOffset);
	fa_[3] = (uint64_t)(int64_t)(writeOffset);
	fa_[4] = (uint64_t)(int64_t)(size);
	fw_call(GLH_OP_glCopyBufferSubData, fa_, 5, NULL, 0);
}

void APIENTRY glCopyTexSubImage2D(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint x,GLint y,GLsizei width,GLsizei height);
void APIENTRY fw_glCopyTexSubImage2D(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint x,GLint y,GLsizei width,GLsizei height)
{
	uint64_t fa_[8];
	if (!glfwd_on()) {
		glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
		return;
	}
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(int64_t)(level);
	fa_[2] = (uint64_t)(int64_t)(xoffset);
	fa_[3] = (uint64_t)(int64_t)(yoffset);
	fa_[4] = (uint64_t)(int64_t)(x);
	fa_[5] = (uint64_t)(int64_t)(y);
	fa_[6] = (uint64_t)(int64_t)(width);
	fa_[7] = (uint64_t)(int64_t)(height);
	fw_call(GLH_OP_glCopyTexSubImage2D, fa_, 8, NULL, 0);
}

void APIENTRY glCullFace(GLenum mode);
void APIENTRY fw_glCullFace(GLenum mode)
{
	uint64_t fa_[1];
	glCullFace(mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glCullFace, fa_, 1, NULL, 0);
}

void APIENTRY glDeleteProgram(GLuint program);
void APIENTRY fw_glDeleteProgram(GLuint program)
{
	uint64_t fa_[1];
	glDeleteProgram(program);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fw_call(GLH_OP_glDeleteProgram, fa_, 1, NULL, 0);
}

void APIENTRY glDeleteShader(GLuint shader);
void APIENTRY fw_glDeleteShader(GLuint shader)
{
	uint64_t fa_[1];
	glDeleteShader(shader);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(shader);
	fw_call(GLH_OP_glDeleteShader, fa_, 1, NULL, 0);
}

void APIENTRY glDepthFunc(GLenum func);
void APIENTRY fw_glDepthFunc(GLenum func)
{
	uint64_t fa_[1];
	glDepthFunc(func);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(func);
	fw_call(GLH_OP_glDepthFunc, fa_, 1, NULL, 0);
}

void APIENTRY glDepthMask(GLboolean flag);
void APIENTRY fw_glDepthMask(GLboolean flag)
{
	uint64_t fa_[1];
	glDepthMask(flag);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(flag);
	fw_call(GLH_OP_glDepthMask, fa_, 1, NULL, 0);
}

void APIENTRY glDepthRange(GLclampd zNear,GLclampd zFar);
void APIENTRY fw_glDepthRange(GLclampd zNear,GLclampd zFar)
{
	uint64_t fa_[2];
	glDepthRange(zNear, zFar);
	if (!glfwd_on())
		return;
	fa_[0] = fw_d(zNear);
	fa_[1] = fw_d(zFar);
	fw_call(GLH_OP_glDepthRange, fa_, 2, NULL, 0);
}

void APIENTRY glDetachShader(GLuint program, GLuint shader);
void APIENTRY fw_glDetachShader(GLuint program, GLuint shader)
{
	uint64_t fa_[2];
	glDetachShader(program, shader);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fa_[1] = (uint64_t)(shader);
	fw_call(GLH_OP_glDetachShader, fa_, 2, NULL, 0);
}

void APIENTRY glDisable(GLenum cap);
void APIENTRY fw_glDisable(GLenum cap)
{
	uint64_t fa_[1];
	glDisable(cap);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(cap);
	fw_call(GLH_OP_glDisable, fa_, 1, NULL, 0);
}

void APIENTRY glDisableVertexAttribArray(GLuint index);
void APIENTRY fw_glDisableVertexAttribArray(GLuint index)
{
	uint64_t fa_[1];
	glDisableVertexAttribArray(index);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fw_call(GLH_OP_glDisableVertexAttribArray, fa_, 1, NULL, 0);
}

void APIENTRY glDisablei(GLenum target, GLuint index);
void APIENTRY fw_glDisablei(GLenum target, GLuint index)
{
	uint64_t fa_[2];
	glDisablei(target, index);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(index);
	fw_call(GLH_OP_glDisablei, fa_, 2, NULL, 0);
}

void APIENTRY glDispatchCompute(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
void APIENTRY fw_glDispatchCompute(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
{
	uint64_t fa_[3];
	if (!glfwd_on()) {
		glDispatchCompute(num_groups_x, num_groups_y, num_groups_z);
		return;
	}
	fa_[0] = (uint64_t)(num_groups_x);
	fa_[1] = (uint64_t)(num_groups_y);
	fa_[2] = (uint64_t)(num_groups_z);
	fw_call(GLH_OP_glDispatchCompute, fa_, 3, NULL, 0);
}

void APIENTRY glDrawBuffer(GLenum mode);
void APIENTRY fw_glDrawBuffer(GLenum mode)
{
	uint64_t fa_[1];
	glDrawBuffer(mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glDrawBuffer, fa_, 1, NULL, 0);
}

void APIENTRY glEnable(GLenum cap);
void APIENTRY fw_glEnable(GLenum cap)
{
	uint64_t fa_[1];
	glEnable(cap);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(cap);
	fw_call(GLH_OP_glEnable, fa_, 1, NULL, 0);
}

void APIENTRY glEnableVertexAttribArray(GLuint index);
void APIENTRY fw_glEnableVertexAttribArray(GLuint index)
{
	uint64_t fa_[1];
	glEnableVertexAttribArray(index);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fw_call(GLH_OP_glEnableVertexAttribArray, fa_, 1, NULL, 0);
}

void APIENTRY glEnablei(GLenum target, GLuint index);
void APIENTRY fw_glEnablei(GLenum target, GLuint index)
{
	uint64_t fa_[2];
	glEnablei(target, index);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(index);
	fw_call(GLH_OP_glEnablei, fa_, 2, NULL, 0);
}

void APIENTRY glEnd(void);
void APIENTRY fw_glEnd(void)
{
	if (!glfwd_on()) {
		glEnd();
		return;
	}
	fw_call(GLH_OP_glEnd, NULL, 0, NULL, 0);
}

void APIENTRY glEndTransformFeedback(void);
void APIENTRY fw_glEndTransformFeedback(void)
{
	glEndTransformFeedback();
	if (!glfwd_on())
		return;
	fw_call(GLH_OP_glEndTransformFeedback, NULL, 0, NULL, 0);
}

void APIENTRY glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void APIENTRY fw_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
	uint64_t fa_[4];
	glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(attachment);
	fa_[2] = (uint64_t)(renderbuffertarget);
	fa_[3] = (uint64_t)(renderbuffer);
	fw_call(GLH_OP_glFramebufferRenderbuffer, fa_, 4, NULL, 0);
}

void APIENTRY glFramebufferTexture(GLenum target, GLenum attachment, GLuint texture, GLint level);
void APIENTRY fw_glFramebufferTexture(GLenum target, GLenum attachment, GLuint texture, GLint level)
{
	uint64_t fa_[4];
	glFramebufferTexture(target, attachment, texture, level);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(attachment);
	fa_[2] = (uint64_t)(texture);
	fa_[3] = (uint64_t)(int64_t)(level);
	fw_call(GLH_OP_glFramebufferTexture, fa_, 4, NULL, 0);
}

void APIENTRY glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void APIENTRY fw_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
	uint64_t fa_[5];
	glFramebufferTexture2D(target, attachment, textarget, texture, level);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(attachment);
	fa_[2] = (uint64_t)(textarget);
	fa_[3] = (uint64_t)(texture);
	fa_[4] = (uint64_t)(int64_t)(level);
	fw_call(GLH_OP_glFramebufferTexture2D, fa_, 5, NULL, 0);
}

void APIENTRY glFrontFace(GLenum mode);
void APIENTRY fw_glFrontFace(GLenum mode)
{
	uint64_t fa_[1];
	glFrontFace(mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glFrontFace, fa_, 1, NULL, 0);
}

void APIENTRY glGenerateMipmap(GLenum target);
void APIENTRY fw_glGenerateMipmap(GLenum target)
{
	uint64_t fa_[1];
	glGenerateMipmap(target);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fw_call(GLH_OP_glGenerateMipmap, fa_, 1, NULL, 0);
}

void APIENTRY glHint(GLenum target,GLenum mode);
void APIENTRY fw_glHint(GLenum target,GLenum mode)
{
	uint64_t fa_[2];
	glHint(target, mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(mode);
	fw_call(GLH_OP_glHint, fa_, 2, NULL, 0);
}

void APIENTRY glLineWidth(GLfloat width);
void APIENTRY fw_glLineWidth(GLfloat width)
{
	uint64_t fa_[1];
	glLineWidth(width);
	if (!glfwd_on())
		return;
	fa_[0] = fw_f(width);
	fw_call(GLH_OP_glLineWidth, fa_, 1, NULL, 0);
}

void APIENTRY glLinkProgram(GLuint program);
void APIENTRY fw_glLinkProgram(GLuint program)
{
	uint64_t fa_[1];
	glLinkProgram(program);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fw_call(GLH_OP_glLinkProgram, fa_, 1, NULL, 0);
}

void APIENTRY glMemoryBarrier(GLbitfield barriers);
void APIENTRY fw_glMemoryBarrier(GLbitfield barriers)
{
	uint64_t fa_[1];
	glMemoryBarrier(barriers);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(barriers);
	fw_call(GLH_OP_glMemoryBarrier, fa_, 1, NULL, 0);
}

void APIENTRY glPointSize(GLfloat size);
void APIENTRY fw_glPointSize(GLfloat size)
{
	uint64_t fa_[1];
	glPointSize(size);
	if (!glfwd_on())
		return;
	fa_[0] = fw_f(size);
	fw_call(GLH_OP_glPointSize, fa_, 1, NULL, 0);
}

void APIENTRY glPolygonMode(GLenum face,GLenum mode);
void APIENTRY fw_glPolygonMode(GLenum face,GLenum mode)
{
	uint64_t fa_[2];
	glPolygonMode(face, mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(face);
	fa_[1] = (uint64_t)(mode);
	fw_call(GLH_OP_glPolygonMode, fa_, 2, NULL, 0);
}

void APIENTRY glPolygonOffset(GLfloat factor,GLfloat units);
void APIENTRY fw_glPolygonOffset(GLfloat factor,GLfloat units)
{
	uint64_t fa_[2];
	glPolygonOffset(factor, units);
	if (!glfwd_on())
		return;
	fa_[0] = fw_f(factor);
	fa_[1] = fw_f(units);
	fw_call(GLH_OP_glPolygonOffset, fa_, 2, NULL, 0);
}

void APIENTRY glReadBuffer(GLenum mode);
void APIENTRY fw_glReadBuffer(GLenum mode)
{
	uint64_t fa_[1];
	glReadBuffer(mode);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mode);
	fw_call(GLH_OP_glReadBuffer, fa_, 1, NULL, 0);
}

void APIENTRY glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void APIENTRY fw_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
	uint64_t fa_[4];
	glRenderbufferStorage(target, internalformat, width, height);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(internalformat);
	fa_[2] = (uint64_t)(int64_t)(width);
	fa_[3] = (uint64_t)(int64_t)(height);
	fw_call(GLH_OP_glRenderbufferStorage, fa_, 4, NULL, 0);
}

void APIENTRY glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param);
void APIENTRY fw_glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param)
{
	uint64_t fa_[3];
	glSamplerParameterf(sampler, pname, param);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(sampler);
	fa_[1] = (uint64_t)(pname);
	fa_[2] = fw_f(param);
	fw_call(GLH_OP_glSamplerParameterf, fa_, 3, NULL, 0);
}

void APIENTRY glSamplerParameteri(GLuint sampler, GLenum pname, GLint param);
void APIENTRY fw_glSamplerParameteri(GLuint sampler, GLenum pname, GLint param)
{
	uint64_t fa_[3];
	glSamplerParameteri(sampler, pname, param);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(sampler);
	fa_[1] = (uint64_t)(pname);
	fa_[2] = (uint64_t)(int64_t)(param);
	fw_call(GLH_OP_glSamplerParameteri, fa_, 3, NULL, 0);
}

void APIENTRY glScissor(GLint x,GLint y,GLsizei width,GLsizei height);
void APIENTRY fw_glScissor(GLint x,GLint y,GLsizei width,GLsizei height)
{
	uint64_t fa_[4];
	glScissor(x, y, width, height);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(x);
	fa_[1] = (uint64_t)(int64_t)(y);
	fa_[2] = (uint64_t)(int64_t)(width);
	fa_[3] = (uint64_t)(int64_t)(height);
	fw_call(GLH_OP_glScissor, fa_, 4, NULL, 0);
}

void APIENTRY glStencilFunc(GLenum func,GLint ref,GLuint mask);
void APIENTRY fw_glStencilFunc(GLenum func,GLint ref,GLuint mask)
{
	uint64_t fa_[3];
	glStencilFunc(func, ref, mask);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(func);
	fa_[1] = (uint64_t)(int64_t)(ref);
	fa_[2] = (uint64_t)(mask);
	fw_call(GLH_OP_glStencilFunc, fa_, 3, NULL, 0);
}

void APIENTRY glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask);
void APIENTRY fw_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask)
{
	uint64_t fa_[4];
	glStencilFuncSeparate(face, func, ref, mask);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(face);
	fa_[1] = (uint64_t)(func);
	fa_[2] = (uint64_t)(int64_t)(ref);
	fa_[3] = (uint64_t)(mask);
	fw_call(GLH_OP_glStencilFuncSeparate, fa_, 4, NULL, 0);
}

void APIENTRY glStencilMask(GLuint mask);
void APIENTRY fw_glStencilMask(GLuint mask)
{
	uint64_t fa_[1];
	glStencilMask(mask);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(mask);
	fw_call(GLH_OP_glStencilMask, fa_, 1, NULL, 0);
}

void APIENTRY glStencilMaskSeparate(GLenum face, GLuint mask);
void APIENTRY fw_glStencilMaskSeparate(GLenum face, GLuint mask)
{
	uint64_t fa_[2];
	glStencilMaskSeparate(face, mask);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(face);
	fa_[1] = (uint64_t)(mask);
	fw_call(GLH_OP_glStencilMaskSeparate, fa_, 2, NULL, 0);
}

void APIENTRY glStencilOp(GLenum fail,GLenum zfail,GLenum zpass);
void APIENTRY fw_glStencilOp(GLenum fail,GLenum zfail,GLenum zpass)
{
	uint64_t fa_[3];
	glStencilOp(fail, zfail, zpass);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(fail);
	fa_[1] = (uint64_t)(zfail);
	fa_[2] = (uint64_t)(zpass);
	fw_call(GLH_OP_glStencilOp, fa_, 3, NULL, 0);
}

void APIENTRY glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void APIENTRY fw_glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass)
{
	uint64_t fa_[4];
	glStencilOpSeparate(face, sfail, dpfail, dppass);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(face);
	fa_[1] = (uint64_t)(sfail);
	fa_[2] = (uint64_t)(dpfail);
	fa_[3] = (uint64_t)(dppass);
	fw_call(GLH_OP_glStencilOpSeparate, fa_, 4, NULL, 0);
}

void APIENTRY glTexCoord2f(GLfloat s,GLfloat t);
void APIENTRY fw_glTexCoord2f(GLfloat s,GLfloat t)
{
	uint64_t fa_[2];
	if (!glfwd_on()) {
		glTexCoord2f(s, t);
		return;
	}
	fa_[0] = fw_f(s);
	fa_[1] = fw_f(t);
	fw_call(GLH_OP_glTexCoord2f, fa_, 2, NULL, 0);
}

void APIENTRY glTexParameterf(GLenum target,GLenum pname,GLfloat param);
void APIENTRY fw_glTexParameterf(GLenum target,GLenum pname,GLfloat param)
{
	uint64_t fa_[3];
	glTexParameterf(target, pname, param);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(pname);
	fa_[2] = fw_f(param);
	fw_call(GLH_OP_glTexParameterf, fa_, 3, NULL, 0);
}

void APIENTRY glTexParameteri(GLenum target,GLenum pname,GLint param);
void APIENTRY fw_glTexParameteri(GLenum target,GLenum pname,GLint param)
{
	uint64_t fa_[3];
	glTexParameteri(target, pname, param);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(pname);
	fa_[2] = (uint64_t)(int64_t)(param);
	fw_call(GLH_OP_glTexParameteri, fa_, 3, NULL, 0);
}

void APIENTRY glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void APIENTRY fw_glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height)
{
	uint64_t fa_[5];
	glTexStorage2D(target, levels, internalformat, width, height);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(target);
	fa_[1] = (uint64_t)(int64_t)(levels);
	fa_[2] = (uint64_t)(internalformat);
	fa_[3] = (uint64_t)(int64_t)(width);
	fa_[4] = (uint64_t)(int64_t)(height);
	fw_call(GLH_OP_glTexStorage2D, fa_, 5, NULL, 0);
}

void APIENTRY glUniform1f(GLint location, GLfloat v0);
void APIENTRY fw_glUniform1f(GLint location, GLfloat v0)
{
	uint64_t fa_[2];
	glUniform1f(location, v0);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = fw_f(v0);
	fw_call(GLH_OP_glUniform1f, fa_, 2, NULL, 0);
}

void APIENTRY glUniform1i(GLint location, GLint v0);
void APIENTRY fw_glUniform1i(GLint location, GLint v0)
{
	uint64_t fa_[2];
	glUniform1i(location, v0);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = (uint64_t)(int64_t)(v0);
	fw_call(GLH_OP_glUniform1i, fa_, 2, NULL, 0);
}

void APIENTRY glUniform1ui(GLint location, GLuint v0);
void APIENTRY fw_glUniform1ui(GLint location, GLuint v0)
{
	uint64_t fa_[2];
	glUniform1ui(location, v0);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = (uint64_t)(v0);
	fw_call(GLH_OP_glUniform1ui, fa_, 2, NULL, 0);
}

void APIENTRY glUniform2f(GLint location, GLfloat v0, GLfloat v1);
void APIENTRY fw_glUniform2f(GLint location, GLfloat v0, GLfloat v1)
{
	uint64_t fa_[3];
	glUniform2f(location, v0, v1);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = fw_f(v0);
	fa_[2] = fw_f(v1);
	fw_call(GLH_OP_glUniform2f, fa_, 3, NULL, 0);
}

void APIENTRY glUniform2i(GLint location, GLint v0, GLint v1);
void APIENTRY fw_glUniform2i(GLint location, GLint v0, GLint v1)
{
	uint64_t fa_[3];
	glUniform2i(location, v0, v1);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = (uint64_t)(int64_t)(v0);
	fa_[2] = (uint64_t)(int64_t)(v1);
	fw_call(GLH_OP_glUniform2i, fa_, 3, NULL, 0);
}

void APIENTRY glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void APIENTRY fw_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
{
	uint64_t fa_[4];
	glUniform3f(location, v0, v1, v2);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = fw_f(v0);
	fa_[2] = fw_f(v1);
	fa_[3] = fw_f(v2);
	fw_call(GLH_OP_glUniform3f, fa_, 4, NULL, 0);
}

void APIENTRY glUniform3i(GLint location, GLint v0, GLint v1, GLint v2);
void APIENTRY fw_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2)
{
	uint64_t fa_[4];
	glUniform3i(location, v0, v1, v2);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = (uint64_t)(int64_t)(v0);
	fa_[2] = (uint64_t)(int64_t)(v1);
	fa_[3] = (uint64_t)(int64_t)(v2);
	fw_call(GLH_OP_glUniform3i, fa_, 4, NULL, 0);
}

void APIENTRY glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void APIENTRY fw_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
{
	uint64_t fa_[5];
	glUniform4f(location, v0, v1, v2, v3);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = fw_f(v0);
	fa_[2] = fw_f(v1);
	fa_[3] = fw_f(v2);
	fa_[4] = fw_f(v3);
	fw_call(GLH_OP_glUniform4f, fa_, 5, NULL, 0);
}

void APIENTRY glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void APIENTRY fw_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3)
{
	uint64_t fa_[5];
	glUniform4i(location, v0, v1, v2, v3);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(location);
	fa_[1] = (uint64_t)(int64_t)(v0);
	fa_[2] = (uint64_t)(int64_t)(v1);
	fa_[3] = (uint64_t)(int64_t)(v2);
	fa_[4] = (uint64_t)(int64_t)(v3);
	fw_call(GLH_OP_glUniform4i, fa_, 5, NULL, 0);
}

void APIENTRY glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void APIENTRY fw_glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
{
	uint64_t fa_[3];
	glUniformBlockBinding(program, uniformBlockIndex, uniformBlockBinding);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fa_[1] = (uint64_t)(uniformBlockIndex);
	fa_[2] = (uint64_t)(uniformBlockBinding);
	fw_call(GLH_OP_glUniformBlockBinding, fa_, 3, NULL, 0);
}

void APIENTRY glUseProgram(GLuint program);
void APIENTRY fw_glUseProgram(GLuint program)
{
	uint64_t fa_[1];
	glUseProgram(program);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(program);
	fw_call(GLH_OP_glUseProgram, fa_, 1, NULL, 0);
}

void APIENTRY glVertex2f(GLfloat x,GLfloat y);
void APIENTRY fw_glVertex2f(GLfloat x,GLfloat y)
{
	uint64_t fa_[2];
	if (!glfwd_on()) {
		glVertex2f(x, y);
		return;
	}
	fa_[0] = fw_f(x);
	fa_[1] = fw_f(y);
	fw_call(GLH_OP_glVertex2f, fa_, 2, NULL, 0);
}

void APIENTRY glVertex3f(GLfloat x,GLfloat y,GLfloat z);
void APIENTRY fw_glVertex3f(GLfloat x,GLfloat y,GLfloat z)
{
	uint64_t fa_[3];
	if (!glfwd_on()) {
		glVertex3f(x, y, z);
		return;
	}
	fa_[0] = fw_f(x);
	fa_[1] = fw_f(y);
	fa_[2] = fw_f(z);
	fw_call(GLH_OP_glVertex3f, fa_, 3, NULL, 0);
}

void APIENTRY glVertexAttrib1f(GLuint index, GLfloat x);
void APIENTRY fw_glVertexAttrib1f(GLuint index, GLfloat x)
{
	uint64_t fa_[2];
	glVertexAttrib1f(index, x);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = fw_f(x);
	fw_call(GLH_OP_glVertexAttrib1f, fa_, 2, NULL, 0);
}

void APIENTRY glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y);
void APIENTRY fw_glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y)
{
	uint64_t fa_[3];
	glVertexAttrib2f(index, x, y);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = fw_f(x);
	fa_[2] = fw_f(y);
	fw_call(GLH_OP_glVertexAttrib2f, fa_, 3, NULL, 0);
}

void APIENTRY glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z);
void APIENTRY fw_glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z)
{
	uint64_t fa_[4];
	glVertexAttrib3f(index, x, y, z);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = fw_f(x);
	fa_[2] = fw_f(y);
	fa_[3] = fw_f(z);
	fw_call(GLH_OP_glVertexAttrib3f, fa_, 4, NULL, 0);
}

void APIENTRY glVertexAttrib4Nub(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
void APIENTRY fw_glVertexAttrib4Nub(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w)
{
	uint64_t fa_[5];
	glVertexAttrib4Nub(index, x, y, z, w);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = (uint64_t)(x);
	fa_[2] = (uint64_t)(y);
	fa_[3] = (uint64_t)(z);
	fa_[4] = (uint64_t)(w);
	fw_call(GLH_OP_glVertexAttrib4Nub, fa_, 5, NULL, 0);
}

void APIENTRY glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void APIENTRY fw_glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
	uint64_t fa_[5];
	glVertexAttrib4f(index, x, y, z, w);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = fw_f(x);
	fa_[2] = fw_f(y);
	fa_[3] = fw_f(z);
	fa_[4] = fw_f(w);
	fw_call(GLH_OP_glVertexAttrib4f, fa_, 5, NULL, 0);
}

void APIENTRY glVertexAttribDivisor(GLuint index, GLuint divisor);
void APIENTRY fw_glVertexAttribDivisor(GLuint index, GLuint divisor)
{
	uint64_t fa_[2];
	glVertexAttribDivisor(index, divisor);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(index);
	fa_[1] = (uint64_t)(divisor);
	fw_call(GLH_OP_glVertexAttribDivisor, fa_, 2, NULL, 0);
}

void APIENTRY glViewport(GLint x,GLint y,GLsizei width,GLsizei height);
void APIENTRY fw_glViewport(GLint x,GLint y,GLsizei width,GLsizei height)
{
	uint64_t fa_[4];
	glViewport(x, y, width, height);
	if (!glfwd_on())
		return;
	fa_[0] = (uint64_t)(int64_t)(x);
	fa_[1] = (uint64_t)(int64_t)(y);
	fa_[2] = (uint64_t)(int64_t)(width);
	fa_[3] = (uint64_t)(int64_t)(height);
	fw_call(GLH_OP_glViewport, fa_, 4, NULL, 0);
}

