/* Generated by gen_gl.py - do not edit. Included by glhost.c. */

typedef void(APIENTRY *T_glActiveTexture)(GLenum texture);
static T_glActiveTexture P_glActiveTexture;
typedef void(APIENTRY *T_glAttachShader)(GLuint program, GLuint shader);
static T_glAttachShader P_glAttachShader;
typedef void(APIENTRY *T_glBegin)(GLenum mode);
static T_glBegin P_glBegin;
typedef void(APIENTRY *T_glBeginTransformFeedback)(GLenum primitiveMode);
static T_glBeginTransformFeedback P_glBeginTransformFeedback;
typedef void(APIENTRY *T_glBindAttribLocation)(GLuint program, GLuint index, const GLchar *name);
static T_glBindAttribLocation P_glBindAttribLocation;
typedef void(APIENTRY *T_glBindBuffer)(GLenum target, GLuint buffer);
static T_glBindBuffer P_glBindBuffer;
typedef void(APIENTRY *T_glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
static T_glBindBufferBase P_glBindBufferBase;
typedef void(APIENTRY *T_glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
static T_glBindBufferRange P_glBindBufferRange;
typedef void(APIENTRY *T_glBindFragDataLocation)(GLuint program, GLuint color, const GLchar *name);
static T_glBindFragDataLocation P_glBindFragDataLocation;
typedef void(APIENTRY *T_glBindFramebuffer)(GLenum target, GLuint framebuffer);
static T_glBindFramebuffer P_glBindFramebuffer;
typedef void(APIENTRY *T_glBindImageTexture)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
static T_glBindImageTexture P_glBindImageTexture;
typedef void(APIENTRY *T_glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
static T_glBindRenderbuffer P_glBindRenderbuffer;
typedef void(APIENTRY *T_glBindSampler)(GLuint unit, GLuint sampler);
static T_glBindSampler P_glBindSampler;
typedef void(APIENTRY *T_glBindTexture)(GLenum target,GLuint texture);
static T_glBindTexture P_glBindTexture;
typedef void(APIENTRY *T_glBindVertexArray)(GLuint array);
static T_glBindVertexArray P_glBindVertexArray;
typedef void(APIENTRY *T_glBlendEquation)(GLenum mode);
static T_glBlendEquation P_glBlendEquation;
typedef void(APIENTRY *T_glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
static T_glBlendEquationSeparate P_glBlendEquationSeparate;
typedef void(APIENTRY *T_glBlendFunc)(GLenum sfactor,GLenum dfactor);
static T_glBlendFunc P_glBlendFunc;
typedef void(APIENTRY *T_glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
static T_glBlendFuncSeparate P_glBlendFuncSeparate;
typedef void(APIENTRY *T_glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
static T_glBlitFramebuffer P_glBlitFramebuffer;
typedef void(APIENTRY *T_glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
static T_glBufferData P_glBufferData;
typedef void(APIENTRY *T_glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
static T_glBufferSubData P_glBufferSubData;
typedef GLenum(APIENTRY *T_glCheckFramebufferStatus)(GLenum target);
static T_glCheckFramebufferStatus P_glCheckFramebufferStatus;
typedef void(APIENTRY *T_glClear)(GLbitfield mask);
static T_glClear P_glClear;
typedef void(APIENTRY *T_glClearColor)(GLclampf red,GLclampf green,GLclampf blue,GLclampf alpha);
static T_glClearColor P_glClearColor;
typedef void(APIENTRY *T_glClearDepth)(GLclampd depth);
static T_glClearDepth P_glClearDepth;
typedef void(APIENTRY *T_glClearDepthf)(GLfloat d);
static T_glClearDepthf P_glClearDepthf;
typedef void(APIENTRY *T_glClearStencil)(GLint s);
static T_glClearStencil P_glClearStencil;
typedef GLenum(APIENTRY *T_glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
static T_glClientWaitSync P_glClientWaitSync;
typedef void(APIENTRY *T_glColor4f)(GLfloat red,GLfloat green,GLfloat blue,GLfloat alpha);
static T_glColor4f P_glColor4f;
typedef void(APIENTRY *T_glColor4ub)(GLubyte red,GLubyte green,GLubyte blue,GLubyte alpha);
static T_glColor4ub P_glColor4ub;
typedef void(APIENTRY *T_glColorMask)(GLboolean red,GLboolean green,GLboolean blue,GLboolean alpha);
static T_glColorMask P_glColorMask;
typedef void(APIENTRY *T_glColorMaski)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
static T_glColorMaski P_glColorMaski;
typedef void(APIENTRY *T_glCompileShader)(GLuint shader);
static T_glCompileShader P_glCompileShader;
typedef void(APIENTRY *T_glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
static T_glCompressedTexImage2D P_glCompressedTexImage2D;
typedef void(APIENTRY *T_glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
static T_glCopyBufferSubData P_glCopyBufferSubData;
typedef void(APIENTRY *T_glCopyTexSubImage2D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLint x,GLint y,GLsizei width,GLsizei height);
static T_glCopyTexSubImage2D P_glCopyTexSubImage2D;
typedef GLuint(APIENTRY *T_glCreateProgram)(void);
static T_glCreateProgram P_glCreateProgram;
typedef GLuint(APIENTRY *T_glCreateShader)(GLenum type);
static T_glCreateShader P_glCreateShader;
typedef void(APIENTRY *T_glCullFace)(GLenum mode);
static T_glCullFace P_glCullFace;
typedef void(APIENTRY *T_glDeleteBuffers)(GLsizei n, const GLuint *buffers);
static T_glDeleteBuffers P_glDeleteBuffers;
typedef void(APIENTRY *T_glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
static T_glDeleteFramebuffers P_glDeleteFramebuffers;
typedef void(APIENTRY *T_glDeleteProgram)(GLuint program);
static T_glDeleteProgram P_glDeleteProgram;
typedef void(APIENTRY *T_glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
static T_glDeleteRenderbuffers P_glDeleteRenderbuffers;
typedef void(APIENTRY *T_glDeleteSamplers)(GLsizei count, const GLuint *samplers);
static T_glDeleteSamplers P_glDeleteSamplers;
typedef void(APIENTRY *T_glDeleteShader)(GLuint shader);
static T_glDeleteShader P_glDeleteShader;
typedef void(APIENTRY *T_glDeleteSync)(GLsync sync);
static T_glDeleteSync P_glDeleteSync;
typedef void(APIENTRY *T_glDeleteTextures)(GLsizei n,const GLuint *textures);
static T_glDeleteTextures P_glDeleteTextures;
typedef void(APIENTRY *T_glDeleteVertexArrays)(GLsizei n, const GLuint *arrays);
static T_glDeleteVertexArrays P_glDeleteVertexArrays;
typedef void(APIENTRY *T_glDepthFunc)(GLenum func);
static T_glDepthFunc P_glDepthFunc;
typedef void(APIENTRY *T_glDepthMask)(GLboolean flag);
static T_glDepthMask P_glDepthMask;
typedef void(APIENTRY *T_glDepthRange)(GLclampd zNear,GLclampd zFar);
static T_glDepthRange P_glDepthRange;
typedef void(APIENTRY *T_glDetachShader)(GLuint program, GLuint shader);
static T_glDetachShader P_glDetachShader;
typedef void(APIENTRY *T_glDisable)(GLenum cap);
static T_glDisable P_glDisable;
typedef void(APIENTRY *T_glDisableVertexAttribArray)(GLuint index);
static T_glDisableVertexAttribArray P_glDisableVertexAttribArray;
typedef void(APIENTRY *T_glDisablei)(GLenum target, GLuint index);
static T_glDisablei P_glDisablei;
typedef void(APIENTRY *T_glDispatchCompute)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
static T_glDispatchCompute P_glDispatchCompute;
typedef void(APIENTRY *T_glDrawArrays)(GLenum mode,GLint first,GLsizei count);
static T_glDrawArrays P_glDrawArrays;
typedef void(APIENTRY *T_glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
static T_glDrawArraysInstanced P_glDrawArraysInstanced;
typedef void(APIENTRY *T_glDrawBuffer)(GLenum mode);
static T_glDrawBuffer P_glDrawBuffer;
typedef void(APIENTRY *T_glDrawBuffers)(GLsizei n, const GLenum *bufs);
static T_glDrawBuffers P_glDrawBuffers;
typedef void(APIENTRY *T_glDrawElements)(GLenum mode,GLsizei count,GLenum type,const GLvoid *indices);
static T_glDrawElements P_glDrawElements;
typedef void(APIENTRY *T_glDrawElementsBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
static T_glDrawElementsBaseVertex P_glDrawElementsBaseVertex;
typedef void(APIENTRY *T_glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
static T_glDrawElementsInstanced P_glDrawElementsInstanced;
typedef void(APIENTRY *T_glDrawElementsInstancedBaseVertex)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
static T_glDrawElementsInstancedBaseVertex P_glDrawElementsInstancedBaseVertex;
typedef void(APIENTRY *T_glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
static T_glDrawRangeElements P_glDrawRangeElements;
typedef void(APIENTRY *T_glEnable)(GLenum cap);
static T_glEnable P_glEnable;
typedef void(APIENTRY *T_glEnableVertexAttribArray)(GLuint index);
static T_glEnableVertexAttribArray P_glEnableVertexAttribArray;
typedef void(APIENTRY *T_glEnablei)(GLenum target, GLuint index);
static T_glEnablei P_glEnablei;
typedef void(APIENTRY *T_glEnd)(void);
static T_glEnd P_glEnd;
typedef void(APIENTRY *T_glEndTransformFeedback)(void);
static T_glEndTransformFeedback P_glEndTransformFeedback;
typedef GLsync(APIENTRY *T_glFenceSync)(GLenum condition, GLbitfield flags);
static T_glFenceSync P_glFenceSync;
typedef void(APIENTRY *T_glFinish)(void);
static T_glFinish P_glFinish;
typedef void(APIENTRY *T_glFlush)(void);
static T_glFlush P_glFlush;
typedef void(APIENTRY *T_glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
static T_glFramebufferRenderbuffer P_glFramebufferRenderbuffer;
typedef void(APIENTRY *T_glFramebufferTexture)(GLenum target, GLenum attachment, GLuint texture, GLint level);
static T_glFramebufferTexture P_glFramebufferTexture;
typedef void(APIENTRY *T_glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
static T_glFramebufferTexture2D P_glFramebufferTexture2D;
typedef void(APIENTRY *T_glFrontFace)(GLenum mode);
static T_glFrontFace P_glFrontFace;
typedef void(APIENTRY *T_glGenBuffers)(GLsizei n, GLuint *buffers);
static T_glGenBuffers P_glGenBuffers;
typedef void(APIENTRY *T_glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
static T_glGenFramebuffers P_glGenFramebuffers;
typedef void(APIENTRY *T_glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
static T_glGenRenderbuffers P_glGenRenderbuffers;
typedef void(APIENTRY *T_glGenSamplers)(GLsizei count, GLuint *samplers);
static T_glGenSamplers P_glGenSamplers;
typedef void(APIENTRY *T_glGenTextures)(GLsizei n,GLuint *textures);
static T_glGenTextures P_glGenTextures;
typedef void(APIENTRY *T_glGenVertexArrays)(GLsizei n, GLuint *arrays);
static T_glGenVertexArrays P_glGenVertexArrays;
typedef void(APIENTRY *T_glGenerateMipmap)(GLenum target);
static T_glGenerateMipmap P_glGenerateMipmap;
typedef GLint(APIENTRY *T_glGetAttribLocation)(GLuint program, const GLchar *name);
static T_glGetAttribLocation P_glGetAttribLocation;
typedef void(APIENTRY *T_glGetBooleanv)(GLenum pname,GLboolean *params);
static T_glGetBooleanv P_glGetBooleanv;
typedef void(APIENTRY *T_glGetDoublev)(GLenum pname,GLdouble *params);
static T_glGetDoublev P_glGetDoublev;
typedef GLenum(APIENTRY *T_glGetError)(void);
static T_glGetError P_glGetError;
typedef void(APIENTRY *T_glGetFloatv)(GLenum pname,GLfloat *params);
static T_glGetFloatv P_glGetFloatv;
typedef void(APIENTRY *T_glGetIntegeri_v)(GLenum target, GLuint index, GLint *data);
static T_glGetIntegeri_v P_glGetIntegeri_v;
typedef void(APIENTRY *T_glGetIntegerv)(GLenum pname,GLint *params);
static T_glGetIntegerv P_glGetIntegerv;
typedef void(APIENTRY *T_glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
static T_glGetProgramInfoLog P_glGetProgramInfoLog;
typedef void(APIENTRY *T_glGetProgramiv)(GLuint program, GLenum pname, GLint *params);
static T_glGetProgramiv P_glGetProgramiv;
typedef void(APIENTRY *T_glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
static T_glGetShaderInfoLog P_glGetShaderInfoLog;
typedef void(APIENTRY *T_glGetShaderiv)(GLuint shader, GLenum pname, GLint *params);
static T_glGetShaderiv P_glGetShaderiv;
typedef const GLubyte *(APIENTRY *T_glGetString)(GLenum name);
static T_glGetString P_glGetString;
typedef const GLubyte *(APIENTRY *T_glGetStringi)(GLenum name, GLuint index);
static T_glGetStringi P_glGetStringi;
typedef void(APIENTRY *T_glGetTexImage)(GLenum target,GLint level,GLenum format,GLenum type,GLvoid *pixels);
static T_glGetTexImage P_glGetTexImage;
typedef void(APIENTRY *T_glGetTexLevelParameteriv)(GLenum target,GLint level,GLenum pname,GLint *params);
static T_glGetTexLevelParameteriv P_glGetTexLevelParameteriv;
typedef void(APIENTRY *T_glGetTexParameteriv)(GLenum target,GLenum pname,GLint *params);
static T_glGetTexParameteriv P_glGetTexParameteriv;
typedef GLuint(APIENTRY *T_glGetUniformBlockIndex)(GLuint program, const GLchar *uniformBlockName);
static T_glGetUniformBlockIndex P_glGetUniformBlockIndex;
typedef GLint(APIENTRY *T_glGetUniformLocation)(GLuint program, const GLchar *name);
static T_glGetUniformLocation P_glGetUniformLocation;
typedef void(APIENTRY *T_glHint)(GLenum target,GLenum mode);
static T_glHint P_glHint;
typedef GLboolean(APIENTRY *T_glIsEnabled)(GLenum cap);
static T_glIsEnabled P_glIsEnabled;
typedef GLboolean(APIENTRY *T_glIsTexture)(GLuint texture);
static T_glIsTexture P_glIsTexture;
typedef void(APIENTRY *T_glLineWidth)(GLfloat width);
static T_glLineWidth P_glLineWidth;
typedef void(APIENTRY *T_glLinkProgram)(GLuint program);
static T_glLinkProgram P_glLinkProgram;
typedef void *(APIENTRY *T_glMapBuffer)(GLenum target, GLenum access);
static T_glMapBuffer P_glMapBuffer;
typedef void *(APIENTRY *T_glMapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
static T_glMapBufferRange P_glMapBufferRange;
typedef void(APIENTRY *T_glMemoryBarrier)(GLbitfield barriers);
static T_glMemoryBarrier P_glMemoryBarrier;
typedef void(APIENTRY *T_glMultiDrawElements)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
static T_glMultiDrawElements P_glMultiDrawElements;
typedef void(APIENTRY *T_glMultiDrawElementsBaseVertex)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex);
static T_glMultiDrawElementsBaseVertex P_glMultiDrawElementsBaseVertex;
typedef void(APIENTRY *T_glPixelStoref)(GLenum pname,GLfloat param);
static T_glPixelStoref P_glPixelStoref;
typedef void(APIENTRY *T_glPixelStorei)(GLenum pname,GLint param);
static T_glPixelStorei P_glPixelStorei;
typedef void(APIENTRY *T_glPointSize)(GLfloat size);
static T_glPointSize P_glPointSize;
typedef void(APIENTRY *T_glPolygonMode)(GLenum face,GLenum mode);
static T_glPolygonMode P_glPolygonMode;
typedef void(APIENTRY *T_glPolygonOffset)(GLfloat factor,GLfloat units);
static T_glPolygonOffset P_glPolygonOffset;
typedef void(APIENTRY *T_glPolygonStipple)(const GLubyte *mask);
static T_glPolygonStipple P_glPolygonStipple;
typedef void(APIENTRY *T_glReadBuffer)(GLenum mode);
static T_glReadBuffer P_glReadBuffer;
typedef void(APIENTRY *T_glReadPixels)(GLint x,GLint y,GLsizei width,GLsizei height,GLenum format,GLenum type,GLvoid *pixels);
static T_glReadPixels P_glReadPixels;
typedef void(APIENTRY *T_glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
static T_glRenderbufferStorage P_glRenderbufferStorage;
typedef void(APIENTRY *T_glSamplerParameterf)(GLuint sampler, GLenum pname, GLfloat param);
static T_glSamplerParameterf P_glSamplerParameterf;
typedef void(APIENTRY *T_glSamplerParameteri)(GLuint sampler, GLenum pname, GLint param);
static T_glSamplerParameteri P_glSamplerParameteri;
typedef void(APIENTRY *T_glScissor)(GLint x,GLint y,GLsizei width,GLsizei height);
static T_glScissor P_glScissor;
typedef void(APIENTRY *T_glShaderSource)(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
static T_glShaderSource P_glShaderSource;
typedef void(APIENTRY *T_glStencilFunc)(GLenum func,GLint ref,GLuint mask);
static T_glStencilFunc P_glStencilFunc;
typedef void(APIENTRY *T_glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
static T_glStencilFuncSeparate P_glStencilFuncSeparate;
typedef void(APIENTRY *T_glStencilMask)(GLuint mask);
static T_glStencilMask P_glStencilMask;
typedef void(APIENTRY *T_glStencilMaskSeparate)(GLenum face, GLuint mask);
static T_glStencilMaskSeparate P_glStencilMaskSeparate;
typedef void(APIENTRY *T_glStencilOp)(GLenum fail,GLenum zfail,GLenum zpass);
static T_glStencilOp P_glStencilOp;
typedef void(APIENTRY *T_glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
static T_glStencilOpSeparate P_glStencilOpSeparate;
typedef void(APIENTRY *T_glTexCoord2f)(GLfloat s,GLfloat t);
static T_glTexCoord2f P_glTexCoord2f;
typedef void(APIENTRY *T_glTexImage2D)(GLenum target,GLint level,GLint internalformat,GLsizei width,GLsizei height,GLint border,GLenum format,GLenum type,const GLvoid *pixels);
static T_glTexImage2D P_glTexImage2D;
typedef void(APIENTRY *T_glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
static T_glTexImage3D P_glTexImage3D;
typedef void(APIENTRY *T_glTexParameterf)(GLenum target,GLenum pname,GLfloat param);
static T_glTexParameterf P_glTexParameterf;
typedef void(APIENTRY *T_glTexParameterfv)(GLenum target,GLenum pname,const GLfloat *params);
static T_glTexParameterfv P_glTexParameterfv;
typedef void(APIENTRY *T_glTexParameteri)(GLenum target,GLenum pname,GLint param);
static T_glTexParameteri P_glTexParameteri;
typedef void(APIENTRY *T_glTexParameteriv)(GLenum target,GLenum pname,const GLint *params);
static T_glTexParameteriv P_glTexParameteriv;
typedef void(APIENTRY *T_glTexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
static T_glTexStorage2D P_glTexStorage2D;
typedef void(APIENTRY *T_glTexSubImage2D)(GLenum target,GLint level,GLint xoffset,GLint yoffset,GLsizei width,GLsizei height,GLenum format,GLenum type,const GLvoid *pixels);
static T_glTexSubImage2D P_glTexSubImage2D;
typedef void(APIENTRY *T_glTransformFeedbackVaryings)(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
static T_glTransformFeedbackVaryings P_glTransformFeedbackVaryings;
typedef void(APIENTRY *T_glUniform1f)(GLint location, GLfloat v0);
static T_glUniform1f P_glUniform1f;
typedef void(APIENTRY *T_glUniform1fv)(GLint location, GLsizei count, const GLfloat *value);
static T_glUniform1fv P_glUniform1fv;
typedef void(APIENTRY *T_glUniform1i)(GLint location, GLint v0);
static T_glUniform1i P_glUniform1i;
typedef void(APIENTRY *T_glUniform1iv)(GLint location, GLsizei count, const GLint *value);
static T_glUniform1iv P_glUniform1iv;
typedef void(APIENTRY *T_glUniform1ui)(GLint location, GLuint v0);
static T_glUniform1ui P_glUniform1ui;
typedef void(APIENTRY *T_glUniform1uiv)(GLint location, GLsizei count, const GLuint *value);
static T_glUniform1uiv P_glUniform1uiv;
typedef void(APIENTRY *T_glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
static T_glUniform2f P_glUniform2f;
typedef void(APIENTRY *T_glUniform2fv)(GLint location, GLsizei count, const GLfloat *value);
static T_glUniform2fv P_glUniform2fv;
typedef void(APIENTRY *T_glUniform2i)(GLint location, GLint v0, GLint v1);
static T_glUniform2i P_glUniform2i;
typedef void(APIENTRY *T_glUniform2iv)(GLint location, GLsizei count, const GLint *value);
static T_glUniform2iv P_glUniform2iv;
typedef void(APIENTRY *T_glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
static T_glUniform3f P_glUniform3f;
typedef void(APIENTRY *T_glUniform3fv)(GLint location, GLsizei count, const GLfloat *value);
static T_glUniform3fv P_glUniform3fv;
typedef void(APIENTRY *T_glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
static T_glUniform3i P_glUniform3i;
typedef void(APIENTRY *T_glUniform3iv)(GLint location, GLsizei count, const GLint *value);
static T_glUniform3iv P_glUniform3iv;
typedef void(APIENTRY *T_glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
static T_glUniform4f P_glUniform4f;
typedef void(APIENTRY *T_glUniform4fv)(GLint location, GLsizei count, const GLfloat *value);
static T_glUniform4fv P_glUniform4fv;
typedef void(APIENTRY *T_glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
static T_glUniform4i P_glUniform4i;
typedef void(APIENTRY *T_glUniform4iv)(GLint location, GLsizei count, const GLint *value);
static T_glUniform4iv P_glUniform4iv;
typedef void(APIENTRY *T_glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
static T_glUniformBlockBinding P_glUniformBlockBinding;
typedef void(APIENTRY *T_glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix2fv P_glUniformMatrix2fv;
typedef void(APIENTRY *T_glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix2x3fv P_glUniformMatrix2x3fv;
typedef void(APIENTRY *T_glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix2x4fv P_glUniformMatrix2x4fv;
typedef void(APIENTRY *T_glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix3fv P_glUniformMatrix3fv;
typedef void(APIENTRY *T_glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix3x2fv P_glUniformMatrix3x2fv;
typedef void(APIENTRY *T_glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix3x4fv P_glUniformMatrix3x4fv;
typedef void(APIENTRY *T_glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix4fv P_glUniformMatrix4fv;
typedef void(APIENTRY *T_glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix4x2fv P_glUniformMatrix4x2fv;
typedef void(APIENTRY *T_glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
static T_glUniformMatrix4x3fv P_glUniformMatrix4x3fv;
typedef GLboolean(APIENTRY *T_glUnmapBuffer)(GLenum target);
static T_glUnmapBuffer P_glUnmapBuffer;
typedef void(APIENTRY *T_glUseProgram)(GLuint program);
static T_glUseProgram P_glUseProgram;
typedef void(APIENTRY *T_glVertex2f)(GLfloat x,GLfloat y);
static T_glVertex2f P_glVertex2f;
typedef void(APIENTRY *T_glVertex2fv)(const GLfloat *v);
static T_glVertex2fv P_glVertex2fv;
typedef void(APIENTRY *T_glVertex3f)(GLfloat x,GLfloat y,GLfloat z);
static T_glVertex3f P_glVertex3f;
typedef void(APIENTRY *T_glVertexAttrib1f)(GLuint index, GLfloat x);
static T_glVertexAttrib1f P_glVertexAttrib1f;
typedef void(APIENTRY *T_glVertexAttrib1fv)(GLuint index, const GLfloat *v);
static T_glVertexAttrib1fv P_glVertexAttrib1fv;
typedef void(APIENTRY *T_glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
static T_glVertexAttrib2f P_glVertexAttrib2f;
typedef void(APIENTRY *T_glVertexAttrib2fv)(GLuint index, const GLfloat *v);
static T_glVertexAttrib2fv P_glVertexAttrib2fv;
typedef void(APIENTRY *T_glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
static T_glVertexAttrib3f P_glVertexAttrib3f;
typedef void(APIENTRY *T_glVertexAttrib3fv)(GLuint index, const GLfloat *v);
static T_glVertexAttrib3fv P_glVertexAttrib3fv;
typedef void(APIENTRY *T_glVertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
static T_glVertexAttrib4Nub P_glVertexAttrib4Nub;
typedef void(APIENTRY *T_glVertexAttrib4Nubv)(GLuint index, const GLubyte *v);
static T_glVertexAttrib4Nubv P_glVertexAttrib4Nubv;
typedef void(APIENTRY *T_glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
static T_glVertexAttrib4f P_glVertexAttrib4f;
typedef void(APIENTRY *T_glVertexAttrib4fv)(GLuint index, const GLfloat *v);
static T_glVertexAttrib4fv P_glVertexAttrib4fv;
typedef void(APIENTRY *T_glVertexAttribDivisor)(GLuint index, GLuint divisor);
static T_glVertexAttribDivisor P_glVertexAttribDivisor;
typedef void(APIENTRY *T_glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
static T_glVertexAttribIPointer P_glVertexAttribIPointer;
typedef void(APIENTRY *T_glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
static T_glVertexAttribPointer P_glVertexAttribPointer;
typedef void(APIENTRY *T_glViewport)(GLint x,GLint y,GLsizei width,GLsizei height);
static T_glViewport P_glViewport;
typedef void(APIENTRY *T_glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
static T_glWaitSync P_glWaitSync;

static int gen_load(void)
{
	int miss = 0;
	P_glActiveTexture = (T_glActiveTexture)glh_proc("glActiveTexture");
	miss += !P_glActiveTexture;
	P_glAttachShader = (T_glAttachShader)glh_proc("glAttachShader");
	miss += !P_glAttachShader;
	P_glBegin = (T_glBegin)glh_proc("glBegin");
	miss += !P_glBegin;
	P_glBeginTransformFeedback = (T_glBeginTransformFeedback)glh_proc("glBeginTransformFeedback");
	miss += !P_glBeginTransformFeedback;
	P_glBindAttribLocation = (T_glBindAttribLocation)glh_proc("glBindAttribLocation");
	P_glBindBuffer = (T_glBindBuffer)glh_proc("glBindBuffer");
	miss += !P_glBindBuffer;
	P_glBindBufferBase = (T_glBindBufferBase)glh_proc("glBindBufferBase");
	miss += !P_glBindBufferBase;
	P_glBindBufferRange = (T_glBindBufferRange)glh_proc("glBindBufferRange");
	miss += !P_glBindBufferRange;
	P_glBindFragDataLocation = (T_glBindFragDataLocation)glh_proc("glBindFragDataLocation");
	P_glBindFramebuffer = (T_glBindFramebuffer)glh_proc("glBindFramebuffer");
	miss += !P_glBindFramebuffer;
	P_glBindImageTexture = (T_glBindImageTexture)glh_proc("glBindImageTexture");
	miss += !P_glBindImageTexture;
	P_glBindRenderbuffer = (T_glBindRenderbuffer)glh_proc("glBindRenderbuffer");
	miss += !P_glBindRenderbuffer;
	P_glBindSampler = (T_glBindSampler)glh_proc("glBindSampler");
	miss += !P_glBindSampler;
	P_glBindTexture = (T_glBindTexture)glh_proc("glBindTexture");
	miss += !P_glBindTexture;
	P_glBindVertexArray = (T_glBindVertexArray)glh_proc("glBindVertexArray");
	miss += !P_glBindVertexArray;
	P_glBlendEquation = (T_glBlendEquation)glh_proc("glBlendEquation");
	miss += !P_glBlendEquation;
	P_glBlendEquationSeparate = (T_glBlendEquationSeparate)glh_proc("glBlendEquationSeparate");
	miss += !P_glBlendEquationSeparate;
	P_glBlendFunc = (T_glBlendFunc)glh_proc("glBlendFunc");
	miss += !P_glBlendFunc;
	P_glBlendFuncSeparate = (T_glBlendFuncSeparate)glh_proc("glBlendFuncSeparate");
	miss += !P_glBlendFuncSeparate;
	P_glBlitFramebuffer = (T_glBlitFramebuffer)glh_proc("glBlitFramebuffer");
	miss += !P_glBlitFramebuffer;
	P_glBufferData = (T_glBufferData)glh_proc("glBufferData");
	P_glBufferSubData = (T_glBufferSubData)glh_proc("glBufferSubData");
	P_glCheckFramebufferStatus = (T_glCheckFramebufferStatus)glh_proc("glCheckFramebufferStatus");
	P_glClear = (T_glClear)glh_proc("glClear");
	miss += !P_glClear;
	P_glClearColor = (T_glClearColor)glh_proc("glClearColor");
	miss += !P_glClearColor;
	P_glClearDepth = (T_glClearDepth)glh_proc("glClearDepth");
	miss += !P_glClearDepth;
	P_glClearDepthf = (T_glClearDepthf)glh_proc("glClearDepthf");
	miss += !P_glClearDepthf;
	P_glClearStencil = (T_glClearStencil)glh_proc("glClearStencil");
	miss += !P_glClearStencil;
	P_glClientWaitSync = (T_glClientWaitSync)glh_proc("glClientWaitSync");
	P_glColor4f = (T_glColor4f)glh_proc("glColor4f");
	miss += !P_glColor4f;
	P_glColor4ub = (T_glColor4ub)glh_proc("glColor4ub");
	miss += !P_glColor4ub;
	P_glColorMask = (T_glColorMask)glh_proc("glColorMask");
	miss += !P_glColorMask;
	P_glColorMaski = (T_glColorMaski)glh_proc("glColorMaski");
	miss += !P_glColorMaski;
	P_glCompileShader = (T_glCompileShader)glh_proc("glCompileShader");
	miss += !P_glCompileShader;
	P_glCompressedTexImage2D = (T_glCompressedTexImage2D)glh_proc("glCompressedTexImage2D");
	P_glCopyBufferSubData = (T_glCopyBufferSubData)glh_proc("glCopyBufferSubData");
	miss += !P_glCopyBufferSubData;
	P_glCopyTexSubImage2D = (T_glCopyTexSubImage2D)glh_proc("glCopyTexSubImage2D");
	miss += !P_glCopyTexSubImage2D;
	P_glCreateProgram = (T_glCreateProgram)glh_proc("glCreateProgram");
	P_glCreateShader = (T_glCreateShader)glh_proc("glCreateShader");
	P_glCullFace = (T_glCullFace)glh_proc("glCullFace");
	miss += !P_glCullFace;
	P_glDeleteBuffers = (T_glDeleteBuffers)glh_proc("glDeleteBuffers");
	P_glDeleteFramebuffers = (T_glDeleteFramebuffers)glh_proc("glDeleteFramebuffers");
	P_glDeleteProgram = (T_glDeleteProgram)glh_proc("glDeleteProgram");
	miss += !P_glDeleteProgram;
	P_glDeleteRenderbuffers = (T_glDeleteRenderbuffers)glh_proc("glDeleteRenderbuffers");
	P_glDeleteSamplers = (T_glDeleteSamplers)glh_proc("glDeleteSamplers");
	P_glDeleteShader = (T_glDeleteShader)glh_proc("glDeleteShader");
	miss += !P_glDeleteShader;
	P_glDeleteSync = (T_glDeleteSync)glh_proc("glDeleteSync");
	P_glDeleteTextures = (T_glDeleteTextures)glh_proc("glDeleteTextures");
	P_glDeleteVertexArrays = (T_glDeleteVertexArrays)glh_proc("glDeleteVertexArrays");
	P_glDepthFunc = (T_glDepthFunc)glh_proc("glDepthFunc");
	miss += !P_glDepthFunc;
	P_glDepthMask = (T_glDepthMask)glh_proc("glDepthMask");
	miss += !P_glDepthMask;
	P_glDepthRange = (T_glDepthRange)glh_proc("glDepthRange");
	miss += !P_glDepthRange;
	P_glDetachShader = (T_glDetachShader)glh_proc("glDetachShader");
	miss += !P_glDetachShader;
	P_glDisable = (T_glDisable)glh_proc("glDisable");
	miss += !P_glDisable;
	P_glDisableVertexAttribArray = (T_glDisableVertexAttribArray)glh_proc("glDisableVertexAttribArray");
	miss += !P_glDisableVertexAttribArray;
	P_glDisablei = (T_glDisablei)glh_proc("glDisablei");
	miss += !P_glDisablei;
	P_glDispatchCompute = (T_glDispatchCompute)glh_proc("glDispatchCompute");
	miss += !P_glDispatchCompute;
	P_glDrawArrays = (T_glDrawArrays)glh_proc("glDrawArrays");
	P_glDrawArraysInstanced = (T_glDrawArraysInstanced)glh_proc("glDrawArraysInstanced");
	P_glDrawBuffer = (T_glDrawBuffer)glh_proc("glDrawBuffer");
	miss += !P_glDrawBuffer;
	P_glDrawBuffers = (T_glDrawBuffers)glh_proc("glDrawBuffers");
	P_glDrawElements = (T_glDrawElements)glh_proc("glDrawElements");
	P_glDrawElementsBaseVertex = (T_glDrawElementsBaseVertex)glh_proc("glDrawElementsBaseVertex");
	P_glDrawElementsInstanced = (T_glDrawElementsInstanced)glh_proc("glDrawElementsInstanced");
	P_glDrawElementsInstancedBaseVertex = (T_glDrawElementsInstancedBaseVertex)glh_proc("glDrawElementsInstancedBaseVertex");
	P_glDrawRangeElements = (T_glDrawRangeElements)glh_proc("glDrawRangeElements");
	P_glEnable = (T_glEnable)glh_proc("glEnable");
	miss += !P_glEnable;
	P_glEnableVertexAttribArray = (T_glEnableVertexAttribArray)glh_proc("glEnableVertexAttribArray");
	miss += !P_glEnableVertexAttribArray;
	P_glEnablei = (T_glEnablei)glh_proc("glEnablei");
	miss += !P_glEnablei;
	P_glEnd = (T_glEnd)glh_proc("glEnd");
	miss += !P_glEnd;
	P_glEndTransformFeedback = (T_glEndTransformFeedback)glh_proc("glEndTransformFeedback");
	miss += !P_glEndTransformFeedback;
	P_glFenceSync = (T_glFenceSync)glh_proc("glFenceSync");
	P_glFinish = (T_glFinish)glh_proc("glFinish");
	P_glFlush = (T_glFlush)glh_proc("glFlush");
	P_glFramebufferRenderbuffer = (T_glFramebufferRenderbuffer)glh_proc("glFramebufferRenderbuffer");
	miss += !P_glFramebufferRenderbuffer;
	P_glFramebufferTexture = (T_glFramebufferTexture)glh_proc("glFramebufferTexture");
	miss += !P_glFramebufferTexture;
	P_glFramebufferTexture2D = (T_glFramebufferTexture2D)glh_proc("glFramebufferTexture2D");
	miss += !P_glFramebufferTexture2D;
	P_glFrontFace = (T_glFrontFace)glh_proc("glFrontFace");
	miss += !P_glFrontFace;
	P_glGenBuffers = (T_glGenBuffers)glh_proc("glGenBuffers");
	P_glGenFramebuffers = (T_glGenFramebuffers)glh_proc("glGenFramebuffers");
	P_glGenRenderbuffers = (T_glGenRenderbuffers)glh_proc("glGenRenderbuffers");
	P_glGenSamplers = (T_glGenSamplers)glh_proc("glGenSamplers");
	P_glGenTextures = (T_glGenTextures)glh_proc("glGenTextures");
	P_glGenVertexArrays = (T_glGenVertexArrays)glh_proc("glGenVertexArrays");
	P_glGenerateMipmap = (T_glGenerateMipmap)glh_proc("glGenerateMipmap");
	miss += !P_glGenerateMipmap;
	P_glGetAttribLocation = (T_glGetAttribLocation)glh_proc("glGetAttribLocation");
	P_glGetBooleanv = (T_glGetBooleanv)glh_proc("glGetBooleanv");
	P_glGetDoublev = (T_glGetDoublev)glh_proc("glGetDoublev");
	P_glGetError = (T_glGetError)glh_proc("glGetError");
	P_glGetFloatv = (T_glGetFloatv)glh_proc("glGetFloatv");
	P_glGetIntegeri_v = (T_glGetIntegeri_v)glh_proc("glGetIntegeri_v");
	P_glGetIntegerv = (T_glGetIntegerv)glh_proc("glGetIntegerv");
	P_glGetProgramInfoLog = (T_glGetProgramInfoLog)glh_proc("glGetProgramInfoLog");
	P_glGetProgramiv = (T_glGetProgramiv)glh_proc("glGetProgramiv");
	P_glGetShaderInfoLog = (T_glGetShaderInfoLog)glh_proc("glGetShaderInfoLog");
	P_glGetShaderiv = (T_glGetShaderiv)glh_proc("glGetShaderiv");
	P_glGetString = (T_glGetString)glh_proc("glGetString");
	P_glGetStringi = (T_glGetStringi)glh_proc("glGetStringi");
	P_glGetTexImage = (T_glGetTexImage)glh_proc("glGetTexImage");
	P_glGetTexLevelParameteriv = (T_glGetTexLevelParameteriv)glh_proc("glGetTexLevelParameteriv");
	P_glGetTexParameteriv = (T_glGetTexParameteriv)glh_proc("glGetTexParameteriv");
	P_glGetUniformBlockIndex = (T_glGetUniformBlockIndex)glh_proc("glGetUniformBlockIndex");
	P_glGetUniformLocation = (T_glGetUniformLocation)glh_proc("glGetUniformLocation");
	P_glHint = (T_glHint)glh_proc("glHint");
	miss += !P_glHint;
	P_glIsEnabled = (T_glIsEnabled)glh_proc("glIsEnabled");
	P_glIsTexture = (T_glIsTexture)glh_proc("glIsTexture");
	P_glLineWidth = (T_glLineWidth)glh_proc("glLineWidth");
	miss += !P_glLineWidth;
	P_glLinkProgram = (T_glLinkProgram)glh_proc("glLinkProgram");
	miss += !P_glLinkProgram;
	P_glMapBuffer = (T_glMapBuffer)glh_proc("glMapBuffer");
	P_glMapBufferRange = (T_glMapBufferRange)glh_proc("glMapBufferRange");
	P_glMemoryBarrier = (T_glMemoryBarrier)glh_proc("glMemoryBarrier");
	miss += !P_glMemoryBarrier;
	P_glMultiDrawElements = (T_glMultiDrawElements)glh_proc("glMultiDrawElements");
	P_glMultiDrawElementsBaseVertex = (T_glMultiDrawElementsBaseVertex)glh_proc("glMultiDrawElementsBaseVertex");
	P_glPixelStoref = (T_glPixelStoref)glh_proc("glPixelStoref");
	P_glPixelStorei = (T_glPixelStorei)glh_proc("glPixelStorei");
	P_glPointSize = (T_glPointSize)glh_proc("glPointSize");
	miss += !P_glPointSize;
	P_glPolygonMode = (T_glPolygonMode)glh_proc("glPolygonMode");
	miss += !P_glPolygonMode;
	P_glPolygonOffset = (T_glPolygonOffset)glh_proc("glPolygonOffset");
	miss += !P_glPolygonOffset;
	P_glPolygonStipple = (T_glPolygonStipple)glh_proc("glPolygonStipple");
	P_glReadBuffer = (T_glReadBuffer)glh_proc("glReadBuffer");
	miss += !P_glReadBuffer;
	P_glReadPixels = (T_glReadPixels)glh_proc("glReadPixels");
	P_glRenderbufferStorage = (T_glRenderbufferStorage)glh_proc("glRenderbufferStorage");
	miss += !P_glRenderbufferStorage;
	P_glSamplerParameterf = (T_glSamplerParameterf)glh_proc("glSamplerParameterf");
	miss += !P_glSamplerParameterf;
	P_glSamplerParameteri = (T_glSamplerParameteri)glh_proc("glSamplerParameteri");
	miss += !P_glSamplerParameteri;
	P_glScissor = (T_glScissor)glh_proc("glScissor");
	miss += !P_glScissor;
	P_glShaderSource = (T_glShaderSource)glh_proc("glShaderSource");
	P_glStencilFunc = (T_glStencilFunc)glh_proc("glStencilFunc");
	miss += !P_glStencilFunc;
	P_glStencilFuncSeparate = (T_glStencilFuncSeparate)glh_proc("glStencilFuncSeparate");
	miss += !P_glStencilFuncSeparate;
	P_glStencilMask = (T_glStencilMask)glh_proc("glStencilMask");
	miss += !P_glStencilMask;
	P_glStencilMaskSeparate = (T_glStencilMaskSeparate)glh_proc("glStencilMaskSeparate");
	miss += !P_glStencilMaskSeparate;
	P_glStencilOp = (T_glStencilOp)glh_proc("glStencilOp");
	miss += !P_glStencilOp;
	P_glStencilOpSeparate = (T_glStencilOpSeparate)glh_proc("glStencilOpSeparate");
	miss += !P_glStencilOpSeparate;
	P_glTexCoord2f = (T_glTexCoord2f)glh_proc("glTexCoord2f");
	miss += !P_glTexCoord2f;
	P_glTexImage2D = (T_glTexImage2D)glh_proc("glTexImage2D");
	P_glTexImage3D = (T_glTexImage3D)glh_proc("glTexImage3D");
	P_glTexParameterf = (T_glTexParameterf)glh_proc("glTexParameterf");
	miss += !P_glTexParameterf;
	P_glTexParameterfv = (T_glTexParameterfv)glh_proc("glTexParameterfv");
	P_glTexParameteri = (T_glTexParameteri)glh_proc("glTexParameteri");
	miss += !P_glTexParameteri;
	P_glTexParameteriv = (T_glTexParameteriv)glh_proc("glTexParameteriv");
	P_glTexStorage2D = (T_glTexStorage2D)glh_proc("glTexStorage2D");
	miss += !P_glTexStorage2D;
	P_glTexSubImage2D = (T_glTexSubImage2D)glh_proc("glTexSubImage2D");
	P_glTransformFeedbackVaryings = (T_glTransformFeedbackVaryings)glh_proc("glTransformFeedbackVaryings");
	P_glUniform1f = (T_glUniform1f)glh_proc("glUniform1f");
	miss += !P_glUniform1f;
	P_glUniform1fv = (T_glUniform1fv)glh_proc("glUniform1fv");
	P_glUniform1i = (T_glUniform1i)glh_proc("glUniform1i");
	miss += !P_glUniform1i;
	P_glUniform1iv = (T_glUniform1iv)glh_proc("glUniform1iv");
	P_glUniform1ui = (T_glUniform1ui)glh_proc("glUniform1ui");
	miss += !P_glUniform1ui;
	P_glUniform1uiv = (T_glUniform1uiv)glh_proc("glUniform1uiv");
	P_glUniform2f = (T_glUniform2f)glh_proc("glUniform2f");
	miss += !P_glUniform2f;
	P_glUniform2fv = (T_glUniform2fv)glh_proc("glUniform2fv");
	P_glUniform2i = (T_glUniform2i)glh_proc("glUniform2i");
	miss += !P_glUniform2i;
	P_glUniform2iv = (T_glUniform2iv)glh_proc("glUniform2iv");
	P_glUniform3f = (T_glUniform3f)glh_proc("glUniform3f");
	miss += !P_glUniform3f;
	P_glUniform3fv = (T_glUniform3fv)glh_proc("glUniform3fv");
	P_glUniform3i = (T_glUniform3i)glh_proc("glUniform3i");
	miss += !P_glUniform3i;
	P_glUniform3iv = (T_glUniform3iv)glh_proc("glUniform3iv");
	P_glUniform4f = (T_glUniform4f)glh_proc("glUniform4f");
	miss += !P_glUniform4f;
	P_glUniform4fv = (T_glUniform4fv)glh_proc("glUniform4fv");
	P_glUniform4i = (T_glUniform4i)glh_proc("glUniform4i");
	miss += !P_glUniform4i;
	P_glUniform4iv = (T_glUniform4iv)glh_proc("glUniform4iv");
	P_glUniformBlockBinding = (T_glUniformBlockBinding)glh_proc("glUniformBlockBinding");
	miss += !P_glUniformBlockBinding;
	P_glUniformMatrix2fv = (T_glUniformMatrix2fv)glh_proc("glUniformMatrix2fv");
	P_glUniformMatrix2x3fv = (T_glUniformMatrix2x3fv)glh_proc("glUniformMatrix2x3fv");
	P_glUniformMatrix2x4fv = (T_glUniformMatrix2x4fv)glh_proc("glUniformMatrix2x4fv");
	P_glUniformMatrix3fv = (T_glUniformMatrix3fv)glh_proc("glUniformMatrix3fv");
	P_glUniformMatrix3x2fv = (T_glUniformMatrix3x2fv)glh_proc("glUniformMatrix3x2fv");
	P_glUniformMatrix3x4fv = (T_glUniformMatrix3x4fv)glh_proc("glUniformMatrix3x4fv");
	P_glUniformMatrix4fv = (T_glUniformMatrix4fv)glh_proc("glUniformMatrix4fv");
	P_glUniformMatrix4x2fv = (T_glUniformMatrix4x2fv)glh_proc("glUniformMatrix4x2fv");
	P_glUniformMatrix4x3fv = (T_glUniformMatrix4x3fv)glh_proc("glUniformMatrix4x3fv");
	P_glUnmapBuffer = (T_glUnmapBuffer)glh_proc("glUnmapBuffer");
	P_glUseProgram = (T_glUseProgram)glh_proc("glUseProgram");
	miss += !P_glUseProgram;
	P_glVertex2f = (T_glVertex2f)glh_proc("glVertex2f");
	miss += !P_glVertex2f;
	P_glVertex2fv = (T_glVertex2fv)glh_proc("glVertex2fv");
	P_glVertex3f = (T_glVertex3f)glh_proc("glVertex3f");
	miss += !P_glVertex3f;
	P_glVertexAttrib1f = (T_glVertexAttrib1f)glh_proc("glVertexAttrib1f");
	miss += !P_glVertexAttrib1f;
	P_glVertexAttrib1fv = (T_glVertexAttrib1fv)glh_proc("glVertexAttrib1fv");
	P_glVertexAttrib2f = (T_glVertexAttrib2f)glh_proc("glVertexAttrib2f");
	miss += !P_glVertexAttrib2f;
	P_glVertexAttrib2fv = (T_glVertexAttrib2fv)glh_proc("glVertexAttrib2fv");
	P_glVertexAttrib3f = (T_glVertexAttrib3f)glh_proc("glVertexAttrib3f");
	miss += !P_glVertexAttrib3f;
	P_glVertexAttrib3fv = (T_glVertexAttrib3fv)glh_proc("glVertexAttrib3fv");
	P_glVertexAttrib4Nub = (T_glVertexAttrib4Nub)glh_proc("glVertexAttrib4Nub");
	miss += !P_glVertexAttrib4Nub;
	P_glVertexAttrib4Nubv = (T_glVertexAttrib4Nubv)glh_proc("glVertexAttrib4Nubv");
	P_glVertexAttrib4f = (T_glVertexAttrib4f)glh_proc("glVertexAttrib4f");
	miss += !P_glVertexAttrib4f;
	P_glVertexAttrib4fv = (T_glVertexAttrib4fv)glh_proc("glVertexAttrib4fv");
	P_glVertexAttribDivisor = (T_glVertexAttribDivisor)glh_proc("glVertexAttribDivisor");
	miss += !P_glVertexAttribDivisor;
	P_glVertexAttribIPointer = (T_glVertexAttribIPointer)glh_proc("glVertexAttribIPointer");
	P_glVertexAttribPointer = (T_glVertexAttribPointer)glh_proc("glVertexAttribPointer");
	P_glViewport = (T_glViewport)glh_proc("glViewport");
	miss += !P_glViewport;
	P_glWaitSync = (T_glWaitSync)glh_proc("glWaitSync");
	return miss;
}

static void hk_glBindBuffer(const uint64_t *a);
static void hk_glBindFramebuffer(const uint64_t *a);
static void hk_glCompileShader(const uint64_t *a);
static void hk_glDeleteProgram(const uint64_t *a);
static void hk_glDeleteShader(const uint64_t *a);
static void hk_glDrawBuffer(const uint64_t *a);
static void hk_glLinkProgram(const uint64_t *a);
static void hk_glReadBuffer(const uint64_t *a);
static void hk_glUseProgram(const uint64_t *a);
static int fb_is_dflt(GLenum target);

static int gen_dispatch(uint32_t op, const uint64_t *a, uint32_t na)
{
	switch (op) {
	case GLH_OP_glActiveTexture:
		if (na < 1)
			return -1;
		P_glActiveTexture((GLenum)a[0]);
		return 1;
	case GLH_OP_glAttachShader:
		if (na < 2)
			return -1;
		P_glAttachShader(xl(GLH_K_OBJ, (GLuint)a[0]), xl(GLH_K_OBJ, (GLuint)a[1]));
		return 1;
	case GLH_OP_glBegin:
		if (na < 1)
			return -1;
		P_glBegin((GLenum)a[0]);
		return 1;
	case GLH_OP_glBeginTransformFeedback:
		if (na < 1)
			return -1;
		P_glBeginTransformFeedback((GLenum)a[0]);
		return 1;
	case GLH_OP_glBindBuffer:
		if (na < 2)
			return -1;
		hk_glBindBuffer(a);
		return 1;
	case GLH_OP_glBindBufferBase:
		if (na < 3)
			return -1;
		P_glBindBufferBase((GLenum)a[0], (GLuint)a[1], xl(GLH_K_BUF, (GLuint)a[2]));
		return 1;
	case GLH_OP_glBindBufferRange:
		if (na < 5)
			return -1;
		P_glBindBufferRange((GLenum)a[0], (GLuint)a[1], xl(GLH_K_BUF, (GLuint)a[2]), (GLintptr)(int64_t)a[3], (GLsizeiptr)(int64_t)a[4]);
		return 1;
	case GLH_OP_glBindFramebuffer:
		if (na < 2)
			return -1;
		hk_glBindFramebuffer(a);
		return 1;
	case GLH_OP_glBindImageTexture:
		if (na < 7)
			return -1;
		P_glBindImageTexture((GLuint)a[0], xl(GLH_K_TEX, (GLuint)a[1]), (GLint)(int64_t)a[2], (GLboolean)a[3], (GLint)(int64_t)a[4], (GLenum)a[5], (GLenum)a[6]);
		return 1;
	case GLH_OP_glBindRenderbuffer:
		if (na < 2)
			return -1;
		P_glBindRenderbuffer((GLenum)a[0], xl(GLH_K_RBO, (GLuint)a[1]));
		return 1;
	case GLH_OP_glBindSampler:
		if (na < 2)
			return -1;
		P_glBindSampler((GLuint)a[0], xl(GLH_K_SAMP, (GLuint)a[1]));
		return 1;
	case GLH_OP_glBindTexture:
		if (na < 2)
			return -1;
		P_glBindTexture((GLenum)a[0], xl(GLH_K_TEX, (GLuint)a[1]));
		return 1;
	case GLH_OP_glBindVertexArray:
		if (na < 1)
			return -1;
		P_glBindVertexArray(xl(GLH_K_VAO, (GLuint)a[0]));
		return 1;
	case GLH_OP_glBlendEquation:
		if (na < 1)
			return -1;
		P_glBlendEquation((GLenum)a[0]);
		return 1;
	case GLH_OP_glBlendEquationSeparate:
		if (na < 2)
			return -1;
		P_glBlendEquationSeparate((GLenum)a[0], (GLenum)a[1]);
		return 1;
	case GLH_OP_glBlendFunc:
		if (na < 2)
			return -1;
		P_glBlendFunc((GLenum)a[0], (GLenum)a[1]);
		return 1;
	case GLH_OP_glBlendFuncSeparate:
		if (na < 4)
			return -1;
		P_glBlendFuncSeparate((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLenum)a[3]);
		return 1;
	case GLH_OP_glBlitFramebuffer:
		if (na < 10)
			return -1;
		P_glBlitFramebuffer((GLint)(int64_t)a[0], (GLint)(int64_t)a[1], (GLint)(int64_t)a[2], (GLint)(int64_t)a[3], (GLint)(int64_t)a[4], (GLint)(int64_t)a[5], (GLint)(int64_t)a[6], (GLint)(int64_t)a[7], (GLbitfield)a[8], (GLenum)a[9]);
		return 1;
	case GLH_OP_glClear:
		if (na < 1)
			return -1;
		P_glClear((GLbitfield)a[0]);
		return 1;
	case GLH_OP_glClearColor:
		if (na < 4)
			return -1;
		P_glClearColor(glh_f(a[0]), glh_f(a[1]), glh_f(a[2]), glh_f(a[3]));
		return 1;
	case GLH_OP_glClearDepth:
		if (na < 1)
			return -1;
		P_glClearDepth(glh_d(a[0]));
		return 1;
	case GLH_OP_glClearDepthf:
		if (na < 1)
			return -1;
		P_glClearDepthf(glh_f(a[0]));
		return 1;
	case GLH_OP_glClearStencil:
		if (na < 1)
			return -1;
		P_glClearStencil((GLint)(int64_t)a[0]);
		return 1;
	case GLH_OP_glColor4f:
		if (na < 4)
			return -1;
		P_glColor4f(glh_f(a[0]), glh_f(a[1]), glh_f(a[2]), glh_f(a[3]));
		return 1;
	case GLH_OP_glColor4ub:
		if (na < 4)
			return -1;
		P_glColor4ub((GLubyte)a[0], (GLubyte)a[1], (GLubyte)a[2], (GLubyte)a[3]);
		return 1;
	case GLH_OP_glColorMask:
		if (na < 4)
			return -1;
		P_glColorMask((GLboolean)a[0], (GLboolean)a[1], (GLboolean)a[2], (GLboolean)a[3]);
		return 1;
	case GLH_OP_glColorMaski:
		if (na < 5)
			return -1;
		P_glColorMaski((GLuint)a[0], (GLboolean)a[1], (GLboolean)a[2], (GLboolean)a[3], (GLboolean)a[4]);
		return 1;
	case GLH_OP_glCompileShader:
		if (na < 1)
			return -1;
		hk_glCompileShader(a);
		return 1;
	case GLH_OP_glCopyBufferSubData:
		if (na < 5)
			return -1;
		P_glCopyBufferSubData((GLenum)a[0], (GLenum)a[1], (GLintptr)(int64_t)a[2], (GLintptr)(int64_t)a[3], (GLsizeiptr)(int64_t)a[4]);
		return 1;
	case GLH_OP_glCopyTexSubImage2D:
		if (na < 8)
			return -1;
		P_glCopyTexSubImage2D((GLenum)a[0], (GLint)(int64_t)a[1], (GLint)(int64_t)a[2], (GLint)(int64_t)a[3], (GLint)(int64_t)a[4], (GLint)(int64_t)a[5], (GLsizei)(int64_t)a[6], (GLsizei)(int64_t)a[7]);
		return 1;
	case GLH_OP_glCullFace:
		if (na < 1)
			return -1;
		P_glCullFace((GLenum)a[0]);
		return 1;
	case GLH_OP_glDeleteProgram:
		if (na < 1)
			return -1;
		hk_glDeleteProgram(a);
		return 1;
	case GLH_OP_glDeleteShader:
		if (na < 1)
			return -1;
		hk_glDeleteShader(a);
		return 1;
	case GLH_OP_glDepthFunc:
		if (na < 1)
			return -1;
		P_glDepthFunc((GLenum)a[0]);
		return 1;
	case GLH_OP_glDepthMask:
		if (na < 1)
			return -1;
		P_glDepthMask((GLboolean)a[0]);
		return 1;
	case GLH_OP_glDepthRange:
		if (na < 2)
			return -1;
		P_glDepthRange(glh_d(a[0]), glh_d(a[1]));
		return 1;
	case GLH_OP_glDetachShader:
		if (na < 2)
			return -1;
		P_glDetachShader(xl(GLH_K_OBJ, (GLuint)a[0]), xl(GLH_K_OBJ, (GLuint)a[1]));
		return 1;
	case GLH_OP_glDisable:
		if (na < 1)
			return -1;
		P_glDisable((GLenum)a[0]);
		return 1;
	case GLH_OP_glDisableVertexAttribArray:
		if (na < 1)
			return -1;
		P_glDisableVertexAttribArray((GLuint)a[0]);
		return 1;
	case GLH_OP_glDisablei:
		if (na < 2)
			return -1;
		P_glDisablei((GLenum)a[0], (GLuint)a[1]);
		return 1;
	case GLH_OP_glDispatchCompute:
		if (na < 3)
			return -1;
		P_glDispatchCompute((GLuint)a[0], (GLuint)a[1], (GLuint)a[2]);
		return 1;
	case GLH_OP_glDrawBuffer:
		if (na < 1)
			return -1;
		hk_glDrawBuffer(a);
		return 1;
	case GLH_OP_glEnable:
		if (na < 1)
			return -1;
		P_glEnable((GLenum)a[0]);
		return 1;
	case GLH_OP_glEnableVertexAttribArray:
		if (na < 1)
			return -1;
		P_glEnableVertexAttribArray((GLuint)a[0]);
		return 1;
	case GLH_OP_glEnablei:
		if (na < 2)
			return -1;
		P_glEnablei((GLenum)a[0], (GLuint)a[1]);
		return 1;
	case GLH_OP_glEnd:
		if (na < 0)
			return -1;
		P_glEnd();
		return 1;
	case GLH_OP_glEndTransformFeedback:
		if (na < 0)
			return -1;
		P_glEndTransformFeedback();
		return 1;
	case GLH_OP_glFramebufferRenderbuffer:
		if (na < 4)
			return -1;
		if (fb_is_dflt((GLenum)a[0]))
			return 1;
		P_glFramebufferRenderbuffer((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], xl(GLH_K_RBO, (GLuint)a[3]));
		return 1;
	case GLH_OP_glFramebufferTexture:
		if (na < 4)
			return -1;
		if (fb_is_dflt((GLenum)a[0]))
			return 1;
		P_glFramebufferTexture((GLenum)a[0], (GLenum)a[1], xl(GLH_K_TEX, (GLuint)a[2]), (GLint)(int64_t)a[3]);
		return 1;
	case GLH_OP_glFramebufferTexture2D:
		if (na < 5)
			return -1;
		if (fb_is_dflt((GLenum)a[0]))
			return 1;
		P_glFramebufferTexture2D((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], xl(GLH_K_TEX, (GLuint)a[3]), (GLint)(int64_t)a[4]);
		return 1;
	case GLH_OP_glFrontFace:
		if (na < 1)
			return -1;
		P_glFrontFace((GLenum)a[0]);
		return 1;
	case GLH_OP_glGenerateMipmap:
		if (na < 1)
			return -1;
		P_glGenerateMipmap((GLenum)a[0]);
		return 1;
	case GLH_OP_glHint:
		if (na < 2)
			return -1;
		P_glHint((GLenum)a[0], (GLenum)a[1]);
		return 1;
	case GLH_OP_glLineWidth:
		if (na < 1)
			return -1;
		P_glLineWidth(glh_f(a[0]));
		return 1;
	case GLH_OP_glLinkProgram:
		if (na < 1)
			return -1;
		hk_glLinkProgram(a);
		return 1;
	case GLH_OP_glMemoryBarrier:
		if (na < 1)
			return -1;
		P_glMemoryBarrier((GLbitfield)a[0]);
		return 1;
	case GLH_OP_glPointSize:
		if (na < 1)
			return -1;
		P_glPointSize(glh_f(a[0]));
		return 1;
	case GLH_OP_glPolygonMode:
		if (na < 2)
			return -1;
		P_glPolygonMode((GLenum)a[0], (GLenum)a[1]);
		return 1;
	case GLH_OP_glPolygonOffset:
		if (na < 2)
			return -1;
		P_glPolygonOffset(glh_f(a[0]), glh_f(a[1]));
		return 1;
	case GLH_OP_glReadBuffer:
		if (na < 1)
			return -1;
		hk_glReadBuffer(a);
		return 1;
	case GLH_OP_glRenderbufferStorage:
		if (na < 4)
			return -1;
		P_glRenderbufferStorage((GLenum)a[0], (GLenum)a[1], (GLsizei)(int64_t)a[2], (GLsizei)(int64_t)a[3]);
		return 1;
	case GLH_OP_glSamplerParameterf:
		if (na < 3)
			return -1;
		P_glSamplerParameterf(xl(GLH_K_SAMP, (GLuint)a[0]), (GLenum)a[1], glh_f(a[2]));
		return 1;
	case GLH_OP_glSamplerParameteri:
		if (na < 3)
			return -1;
		P_glSamplerParameteri(xl(GLH_K_SAMP, (GLuint)a[0]), (GLenum)a[1], (GLint)(int64_t)a[2]);
		return 1;
	case GLH_OP_glScissor:
		if (na < 4)
			return -1;
		P_glScissor((GLint)(int64_t)a[0], (GLint)(int64_t)a[1], (GLsizei)(int64_t)a[2], (GLsizei)(int64_t)a[3]);
		return 1;
	case GLH_OP_glStencilFunc:
		if (na < 3)
			return -1;
		P_glStencilFunc((GLenum)a[0], (GLint)(int64_t)a[1], (GLuint)a[2]);
		return 1;
	case GLH_OP_glStencilFuncSeparate:
		if (na < 4)
			return -1;
		P_glStencilFuncSeparate((GLenum)a[0], (GLenum)a[1], (GLint)(int64_t)a[2], (GLuint)a[3]);
		return 1;
	case GLH_OP_glStencilMask:
		if (na < 1)
			return -1;
		P_glStencilMask((GLuint)a[0]);
		return 1;
	case GLH_OP_glStencilMaskSeparate:
		if (na < 2)
			return -1;
		P_glStencilMaskSeparate((GLenum)a[0], (GLuint)a[1]);
		return 1;
	case GLH_OP_glStencilOp:
		if (na < 3)
			return -1;
		P_glStencilOp((GLenum)a[0], (GLenum)a[1], (GLenum)a[2]);
		return 1;
	case GLH_OP_glStencilOpSeparate:
		if (na < 4)
			return -1;
		P_glStencilOpSeparate((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLenum)a[3]);
		return 1;
	case GLH_OP_glTexCoord2f:
		if (na < 2)
			return -1;
		P_glTexCoord2f(glh_f(a[0]), glh_f(a[1]));
		return 1;
	case GLH_OP_glTexParameterf:
		if (na < 3)
			return -1;
		P_glTexParameterf((GLenum)a[0], (GLenum)a[1], glh_f(a[2]));
		return 1;
	case GLH_OP_glTexParameteri:
		if (na < 3)
			return -1;
		P_glTexParameteri((GLenum)a[0], (GLenum)a[1], (GLint)(int64_t)a[2]);
		return 1;
	case GLH_OP_glTexStorage2D:
		if (na < 5)
			return -1;
		P_glTexStorage2D((GLenum)a[0], (GLsizei)(int64_t)a[1], (GLenum)a[2], (GLsizei)(int64_t)a[3], (GLsizei)(int64_t)a[4]);
		return 1;
	case GLH_OP_glUniform1f:
		if (na < 2)
			return -1;
		P_glUniform1f(xl_loc((GLint)(int64_t)a[0]), glh_f(a[1]));
		return 1;
	case GLH_OP_glUniform1i:
		if (na < 2)
			return -1;
		P_glUniform1i(xl_loc((GLint)(int64_t)a[0]), (GLint)(int64_t)a[1]);
		return 1;
	case GLH_OP_glUniform1ui:
		if (na < 2)
			return -1;
		P_glUniform1ui(xl_loc((GLint)(int64_t)a[0]), (GLuint)a[1]);
		return 1;
	case GLH_OP_glUniform2f:
		if (na < 3)
			return -1;
		P_glUniform2f(xl_loc((GLint)(int64_t)a[0]), glh_f(a[1]), glh_f(a[2]));
		return 1;
	case GLH_OP_glUniform2i:
		if (na < 3)
			return -1;
		P_glUniform2i(xl_loc((GLint)(int64_t)a[0]), (GLint)(int64_t)a[1], (GLint)(int64_t)a[2]);
		return 1;
	case GLH_OP_glUniform3f:
		if (na < 4)
			return -1;
		P_glUniform3f(xl_loc((GLint)(int64_t)a[0]), glh_f(a[1]), glh_f(a[2]), glh_f(a[3]));
		return 1;
	case GLH_OP_glUniform3i:
		if (na < 4)
			return -1;
		P_glUniform3i(xl_loc((GLint)(int64_t)a[0]), (GLint)(int64_t)a[1], (GLint)(int64_t)a[2], (GLint)(int64_t)a[3]);
		return 1;
	case GLH_OP_glUniform4f:
		if (na < 5)
			return -1;
		P_glUniform4f(xl_loc((GLint)(int64_t)a[0]), glh_f(a[1]), glh_f(a[2]), glh_f(a[3]), glh_f(a[4]));
		return 1;
	case GLH_OP_glUniform4i:
		if (na < 5)
			return -1;
		P_glUniform4i(xl_loc((GLint)(int64_t)a[0]), (GLint)(int64_t)a[1], (GLint)(int64_t)a[2], (GLint)(int64_t)a[3], (GLint)(int64_t)a[4]);
		return 1;
	case GLH_OP_glUniformBlockBinding:
		if (na < 3)
			return -1;
		P_glUniformBlockBinding(xl(GLH_K_OBJ, (GLuint)a[0]), (GLuint)a[1], (GLuint)a[2]);
		return 1;
	case GLH_OP_glUseProgram:
		if (na < 1)
			return -1;
		hk_glUseProgram(a);
		return 1;
	case GLH_OP_glVertex2f:
		if (na < 2)
			return -1;
		P_glVertex2f(glh_f(a[0]), glh_f(a[1]));
		return 1;
	case GLH_OP_glVertex3f:
		if (na < 3)
			return -1;
		P_glVertex3f(glh_f(a[0]), glh_f(a[1]), glh_f(a[2]));
		return 1;
	case GLH_OP_glVertexAttrib1f:
		if (na < 2)
			return -1;
		P_glVertexAttrib1f((GLuint)a[0], glh_f(a[1]));
		return 1;
	case GLH_OP_glVertexAttrib2f:
		if (na < 3)
			return -1;
		P_glVertexAttrib2f((GLuint)a[0], glh_f(a[1]), glh_f(a[2]));
		return 1;
	case GLH_OP_glVertexAttrib3f:
		if (na < 4)
			return -1;
		P_glVertexAttrib3f((GLuint)a[0], glh_f(a[1]), glh_f(a[2]), glh_f(a[3]));
		return 1;
	case GLH_OP_glVertexAttrib4Nub:
		if (na < 5)
			return -1;
		P_glVertexAttrib4Nub((GLuint)a[0], (GLubyte)a[1], (GLubyte)a[2], (GLubyte)a[3], (GLubyte)a[4]);
		return 1;
	case GLH_OP_glVertexAttrib4f:
		if (na < 5)
			return -1;
		P_glVertexAttrib4f((GLuint)a[0], glh_f(a[1]), glh_f(a[2]), glh_f(a[3]), glh_f(a[4]));
		return 1;
	case GLH_OP_glVertexAttribDivisor:
		if (na < 2)
			return -1;
		P_glVertexAttribDivisor((GLuint)a[0], (GLuint)a[1]);
		return 1;
	case GLH_OP_glViewport:
		if (na < 4)
			return -1;
		P_glViewport((GLint)(int64_t)a[0], (GLint)(int64_t)a[1], (GLsizei)(int64_t)a[2], (GLsizei)(int64_t)a[3]);
		return 1;
	}
	return 0;
}
